import type { Request, Response } from "express";
import { db } from "../../database/db.js";
import { risks } from "../../schema/risks/risks.js";
import { riskTop5Mitigations } from "../../schema/risks/riskTop5Mitigations.js";
import { getTop5RisksWithMitigations } from "../../services/getTop5RisksFromAssessmentContext.js";

/**
 * POST /buyerCotsAssessment/autoGenerated
 * Auto-Generated section per AI EVAL Database Fields Reference (Buyer Side CSV).
 * Returns values aligned with Notes: risk linkage, domain-level scoring, context adjustments, mitigation tactics.
 *
 * Contextual multipliers Intent comes from AI Risk Intellect when the Controls API key
 * is set (extra step after AI-Q risk DB match); otherwise falls back to local/default.
 */
const getBuyerCotsAutoGenerated = async (req: Request, res: Response) => {
  try {
    const body = req.body ?? {};
    const _formData = {
      businessPainPoint: body.businessPainPoint ?? body.business_pain_point,
      vendorName: body.vendorName ?? body.vendor_name,
      dataSensitivity: body.dataSensitivity ?? body.data_sensitivity,
      regulatoryRequirements: body.regulatoryRequirements ?? body.regulatory_requirements,
      riskAppetite: body.riskAppetite ?? body.risk_appetite,
    };

    // 1) Identified Risks – CSV: "Risk linkage based on sector, use case, and AI capabilities". Risk IDs and titles from DB.
    const risksRows = await db.select().from(risks);
    const identifiedRisks =
      risksRows.length === 0
        ? "No risks defined in the system yet."
        : risksRows
            .map((r) => `${r.risk_id}: ${r.title}`)
            .join("\n");

    // 2) Risk Domain Scores – CSV: "Domain-level scoring for risk reporting", "Used in buyer readiness score calculation". Format: e.g. "Privacy: 72, AI Safety: 45".
    const domainCounts = risksRows.reduce<Record<string, number>>((acc, r) => {
      const domain = r.domain ?? "Other";
      acc[domain] = (acc[domain] ?? 0) + 1;
      return acc;
    }, {});
    const riskDomainScores =
      Object.keys(domainCounts).length === 0
        ? "No risk domains available."
        : Object.entries(domainCounts)
            .map(([domain, count]) => `${domain}: ${count}`)
            .join(", ");

    // 3) Contextual Multipliers – Intent from AI Risk Intellect when API key is configured.
    let contextualMultipliers =
      "Intent: Mixed (1.0), Timing: Pre-deployment (contextual multipliers can be extended when rules are defined).";
    try {
      const top5 = await getTop5RisksWithMitigations({
        industry_sector: body.industrySector ?? body.industry_sector,
        industry: body.industry,
        business_pain_point: _formData.businessPainPoint,
        regulatory_requirements: _formData.regulatoryRequirements,
        identified_risks: body.identifiedRisks ?? body.identified_risks,
        customer_specific_risks: body.customerSpecificRisks ?? body.customer_specific_risks,
        risk_mitigation_mapping_ids:
          body.riskMitigationMappingIds ?? body.risk_mitigation_mapping_ids,
      });
      if (top5.intentScore?.label) {
        contextualMultipliers = `${top5.intentScore.label}, Timing: Pre-deployment`;
      }
    } catch (e) {
      console.error("autoGenerated intent enrichment failed:", e);
    }

    // 4) Buyer Risk Mitigation – CSV: "Auto-recommended mitigation tactics mapped to identified risks". From risk_top5_mitigations; return display text + mapping_ids for storage.
    const mitigationsRows = await db.select().from(riskTop5Mitigations);
    const riskMitigationMappingIds = mitigationsRows.map((m) => m.mapping_id);
    const riskMitigation =
      mitigationsRows.length === 0
        ? "No risk mitigations defined in the system yet."
        : mitigationsRows
            .map((m) => {
              const parts = [`[${m.risk_id}] ${m.mitigation_action_name} (${m.mitigation_category})`];
              if (m.mitigation_definition) parts.push(` – ${m.mitigation_definition}`);
              return parts.join("");
            })
            .join("\n\n");

    return res.status(200).json({
      data: {
        identifiedRisks,
        riskDomainScores,
        contextualMultipliers,
        riskMitigation,
        riskMitigationMappingIds,
      },
    });
  } catch (error) {
    console.error(
      "Error in getBuyerCotsAutoGenerated:",
      error instanceof Error ? error.message : String(error)
    );
    return res.status(500).json({ message: "Internal server error" });
  }
};

export default getBuyerCotsAutoGenerated;
