import type { Request, Response } from "express";
import { db } from "../../database/db.js";
import { risks } from "../../schema/risks/risks.js";
import { riskTop5Mitigations } from "../../schema/risks/riskTop5Mitigations.js";

/**
 * POST /buyerCotsAssessment/autoGenerated
 * Auto-Generated section per AI EVAL Database Fields Reference (Buyer Side CSV).
 * Returns values aligned with Notes: risk linkage, domain-level scoring, context adjustments, mitigation tactics.
 */
const getBuyerCotsAutoGenerated = async (req: Request, res: Response) => {
  try {
    const body = req.body ?? {};
    const _formData = {
      businessPainPoint: body.businessPainPoint ?? body.business_pain_point,
      vendorName: body.vendorName ?? body.vendor_name,
      dataSensitivity: body.dataSensitivity ?? body.data_sensitivity,
      regulatoryRequirements: body.regulatoryRequirements ?? body.regulatory_requirements,
      riskAppetite: body.riskAppetite ?? body.risk_appetite,
    };

    // 1) Identified Risks – CSV: "Risk linkage based on sector, use case, and AI capabilities". Risk IDs and titles from DB.
    const risksRows = await db.select().from(risks);
    const identifiedRisks =
      risksRows.length === 0
        ? "No risks defined in the system yet."
        : risksRows
            .map((r) => `${r.risk_id}: ${r.title}`)
            .join("\n");

    // 2) Risk Domain Scores – CSV: "Domain-level scoring for risk reporting", "Used in buyer readiness score calculation". Format: e.g. "Privacy: 72, AI Safety: 45".
    const domainCounts = risksRows.reduce<Record<string, number>>((acc, r) => {
      const domain = r.domain ?? "Other";
      acc[domain] = (acc[domain] ?? 0) + 1;
      return acc;
    }, {});
    const riskDomainScores =
      Object.keys(domainCounts).length === 0
        ? "No risk domains available."
        : Object.entries(domainCounts)
            .map(([domain, count]) => `${domain}: ${count}`)
            .join(", ");

    // 3) Contextual Multipliers – CSV: "Risk calculation components showing context adjustments", "Intent, Timing (multipliers)".
    const contextualMultipliers =
      "Intent: Unintentional, Timing: Pre-deployment (contextual multipliers can be extended when rules are defined).";

    // 4) Buyer Risk Mitigation – CSV: "Auto-recommended mitigation tactics mapped to identified risks". From risk_top5_mitigations; return display text + mapping_ids for storage.
    const mitigationsRows = await db.select().from(riskTop5Mitigations);
    const riskMitigationMappingIds = mitigationsRows.map((m) => m.mapping_id);
    const riskMitigation =
      mitigationsRows.length === 0
        ? "No risk mitigations defined in the system yet."
        : mitigationsRows
            .map((m) => {
              const parts = [`[${m.risk_id}] ${m.mitigation_action_name} (${m.mitigation_category})`];
              if (m.mitigation_definition) parts.push(` – ${m.mitigation_definition}`);
              return parts.join("");
            })
            .join("\n\n");

    return res.status(200).json({
      data: {
        identifiedRisks,
        riskDomainScores,
        contextualMultipliers,
        riskMitigation,
        riskMitigationMappingIds,
      },
    });
  } catch (error) {
    console.error(
      "Error in getBuyerCotsAutoGenerated:",
      error instanceof Error ? error.message : String(error)
    );
    return res.status(500).json({ message: "Internal server error" });
  }
};

export default getBuyerCotsAutoGenerated;
