import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
  integer,
} from "drizzle-orm/pg-core";

export const cotsVendorAssessments = pgTable("cots_vendor_assessments", {
  id: uuid("id").defaultRandom().primaryKey(),
  assessment_id: uuid("assessment_id").notNull(),
  user_id: integer("user_id"),
  vendor_attestation_id: uuid("vendor_attestation_id"),
  customer_organization_name: varchar("customer_organization_name", { length: 200 }),
  customer_sector: varchar("customer_sector", { length: 200 }),
  primary_pain_point: text("primary_pain_point"),
  expected_outcomes: varchar("expected_outcomes", { length: 300 }),
  customer_budget_range: varchar("customer_budget_range", { length: 100 }),
  implementation_timeline: varchar("implementation_timeline", { length: 100 }),
  product_features: jsonb("product_features"),
  implementation_approach: varchar("implementation_approach", { length: 100 }),
  customization_level: varchar("customization_level", { length: 100 }),
  integration_complexity: varchar("integration_complexity", { length: 100 }),
  regulatory_requirements: jsonb("regulatory_requirements"),
  regulatory_requirements_other: varchar("regulatory_requirements_other", { length: 300 }),
  data_sensitivity: varchar("data_sensitivity", { length: 100 }),
  customer_risk_tolerance: varchar("customer_risk_tolerance", { length: 100 }),
  alternatives_considered: text("alternatives_considered"),
  key_advantages: text("key_advantages"),
  customer_specific_risks: jsonb("customer_specific_risks"),
  customer_specific_risks_other: varchar("customer_specific_risks_other", { length: 300 }),
  identified_risks: text("identified_risks"),
  risk_domain_scores: text("risk_domain_scores"),
  contextual_multipliers: text("contextual_multipliers"),
  risk_mitigation: text("risk_mitigation"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
