import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
  integer,
} from "drizzle-orm/pg-core";

/** Aligned with Excel "buyer_cots" sheet (column order matches nested sheet). */
export const cotsBuyerAssessments = pgTable("cots_buyer_assessments", {
  id: uuid("id").defaultRandom().primaryKey(),
  buyer_cots_id: uuid("buyer_cots_id").unique().defaultRandom(),
  user_id: integer("user_id"),
  organization_id: varchar("organization_id", { length: 255 }),
  organization_name: varchar("organization_name", { length: 255 }),
  industry: varchar("industry", { length: 200 }),
  industry_sector: varchar("industry_sector", { length: 200 }),
  employee_count: varchar("employee_count", { length: 100 }),
  geographic_regions: jsonb("geographic_regions"),
  pain_point: text("pain_point"),
  business_outcomes: text("business_outcomes"),
  business_unit: varchar("business_unit", { length: 100 }),
  budget_range: varchar("budget_range", { length: 100 }),
  target_timeline: varchar("target_timeline", { length: 100 }),
  critical_of_ai_solution: varchar("critical_of_ai_solution", { length: 100 }),
  vendor_name: varchar("vendor_name", { length: 200 }),
  specific_product: varchar("specific_product", { length: 200 }),
  gap_requirement_product: text("gap_requirement_product"),
  integrate_system: jsonb("integrate_system"),
  integrate_system_other: varchar("integrate_system_other", { length: 300 }),
  current_tech_stack: jsonb("current_tech_stack"),
  digital_maturity: varchar("digital_maturity", { length: 100 }),
  governance_maturity: varchar("governance_maturity", { length: 100 }),
  ai_governance_board: varchar("ai_governance_board", { length: 100 }),
  ai_ethics_policy: varchar("ai_ethics_policy", { length: 100 }),
  team_composition: jsonb("team_composition"),
  data_sensitivity_level: varchar("data_sensitivity_level", { length: 100 }),
  regulatory_requirments: jsonb("regulatory_requirments"),
  risk_appetite: varchar("risk_appetite", { length: 100 }),
  statke_at_ai_decisions: varchar("statke_at_ai_decisions", { length: 100 }),
  impact_by_ai: jsonb("impact_by_ai"),
  vendor_capabilities: varchar("vendor_capabilities", { length: 100 }),
  vendor_security_posture: varchar("vendor_security_posture", { length: 100 }),
  vendor_compliance_certifications: jsonb("vendor_compliance_certifications"),
  phased_rollout_plan: varchar("phased_rollout_plan", { length: 100 }),
  rollback_capability: varchar("rollback_capability", { length: 100 }),
  management_plan: varchar("management_plan", { length: 100 }),
  compliance_document: text("compliance_document"),
  vendor_usage_data: varchar("vendor_usage_data", { length: 100 }),
  audit_logs: varchar("audit_logs", { length: 100 }),
  testing_results: varchar("testing_results", { length: 100 }),
  identified_risks: text("identified_risks"),
  risk_domain_scores: text("risk_domain_scores"),
  contextual_multipliers: text("contextual_multipliers"),
  buyer_risk_mitigation: text("buyer_risk_mitigation"),
  use_case_types: jsonb("use_case_types"),
  users_in_scope: varchar("users_in_scope", { length: 20 }),
  current_usage_state: varchar("current_usage_state", { length: 80 }),
  pilot_status: varchar("pilot_status", { length: 80 }),
  accountable_owner_name: varchar("accountable_owner_name", { length: 200 }),
  accountable_owner_role: varchar("accountable_owner_role", { length: 40 }),
  data_classes: jsonb("data_classes"),
  data_subject_jurisdictions: jsonb("data_subject_jurisdictions"),
  decision_domains: jsonb("decision_domains"),
  output_exposure: varchar("output_exposure", { length: 80 }),
  regulatory_requirements_derived: jsonb("regulatory_requirements_derived"),
  regulatory_requirements_added: jsonb("regulatory_requirements_added"),
  regulatory_requirements_removed: jsonb("regulatory_requirements_removed"),
  retention_requirement: varchar("retention_requirement", { length: 30 }),
  training_use_of_data: varchar("training_use_of_data", { length: 80 }),
  training_use_of_data_stance: varchar("training_use_of_data_stance", { length: 20 }),
  training_use_of_data_dispute_note: text("training_use_of_data_dispute_note"),
  human_review_level: varchar("human_review_level", { length: 80 }),
  ai_disclosure: varchar("ai_disclosure", { length: 40 }),
  deployment_model: varchar("deployment_model", { length: 80 }),
  cloud_provider: jsonb("cloud_provider"),
  integration_access_levels: jsonb("integration_access_levels"),
  implementation_capacity: varchar("implementation_capacity", { length: 80 }),
  training_effort: varchar("training_effort", { length: 80 }),
  vendor_evidence_received: jsonb("vendor_evidence_received"),
  monitoring_data_stance: varchar("monitoring_data_stance", { length: 20 }),
  monitoring_data_dispute_note: text("monitoring_data_dispute_note"),
  audit_logs_stance: varchar("audit_logs_stance", { length: 20 }),
  audit_logs_dispute_note: text("audit_logs_dispute_note"),
  data_export_capability: varchar("data_export_capability", { length: 80 }),
  data_export_stance: varchar("data_export_stance", { length: 20 }),
  data_export_dispute_note: text("data_export_dispute_note"),
  unavailability_impact: varchar("unavailability_impact", { length: 80 }),
  contracts_in_place: jsonb("contracts_in_place"),
  contract_notice_period: varchar("contract_notice_period", { length: 30 }),
  assessor_name: varchar("assessor_name", { length: 200 }),
  assessor_role: varchar("assessor_role", { length: 40 }),
  answer_confidence: varchar("answer_confidence", { length: 80 }),
  review_due_date: timestamp("review_due_date", { withTimezone: true }),
  unlinked_vendor: varchar("unlinked_vendor", { length: 10 }),
  target_outcome_metric: varchar("target_outcome_metric", { length: 120 }),
  target_outcome_baseline: varchar("target_outcome_baseline", { length: 80 }),
  target_outcome_target: varchar("target_outcome_target", { length: 80 }),
  assessment_id: uuid("assessment_id").notNull(),
  risk_mitigation_mapping_ids: jsonb("risk_mitigation_mapping_ids"),
  /** Generated on submit: full Vendor Risk Assessment Report (buyer + attestation). */
  vendor_risk_assessment_report: jsonb("vendor_risk_assessment_report"),
  /** Full IRS rationale block (same as terminal); denormalized for admin i-icon reads. */
  score_rationale: text("score_rationale"),
  score_rationale_type: varchar("score_rationale_type", { length: 8 }),
  /** Controls LLM used when the vendor risk assessment report was generated. */
  llm_model_id: varchar("llm_model_id", { length: 512 }),
  llm_model_label: varchar("llm_model_label", { length: 512 }),
  /** Set when assessment expires: frozen JSON; live vendor_risk_assessment_report is cleared. */
  archived_vendor_risk_assessment_report: jsonb("archived_vendor_risk_assessment_report"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
