import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
  integer,
  date,
} from "drizzle-orm/pg-core";

export const cotsVendorAssessments = pgTable("cots_vendor_assessments", {
  id: uuid("id").defaultRandom().primaryKey(),
  assessment_id: uuid("assessment_id").notNull(),
  user_id: integer("user_id"),
  vendor_attestation_id: uuid("vendor_attestation_id"),
  customer_organization_name: varchar("customer_organization_name", { length: 200 }),
  customer_sector: varchar("customer_sector", { length: 200 }),
  primary_pain_point: text("primary_pain_point"),
  expected_outcomes: text("expected_outcomes"),
  customer_budget_range: varchar("customer_budget_range", { length: 100 }),
  implementation_timeline: varchar("implementation_timeline", { length: 100 }),
  product_features: jsonb("product_features"),
  implementation_approach: varchar("implementation_approach", { length: 100 }),
  customization_level: varchar("customization_level", { length: 100 }),
  integration_complexity: varchar("integration_complexity", { length: 100 }),
  regulatory_requirements: jsonb("regulatory_requirements"),
  regulatory_requirements_other: varchar("regulatory_requirements_other", { length: 300 }),
  data_sensitivity: varchar("data_sensitivity", { length: 100 }),
  customer_risk_tolerance: varchar("customer_risk_tolerance", { length: 100 }),
  alternatives_considered: text("alternatives_considered"),
  key_advantages: text("key_advantages"),
  customer_specific_risks: jsonb("customer_specific_risks"),
  customer_specific_risks_other: varchar("customer_specific_risks_other", { length: 300 }),
  identified_risks: text("identified_risks"),
  risk_domain_scores: text("risk_domain_scores"),
  contextual_multipliers: text("contextual_multipliers"),
  risk_mitigation: text("risk_mitigation"),
  customer_employee_count: varchar("customer_employee_count", { length: 20 }),
  customer_eng_headcount: varchar("customer_eng_headcount", { length: 20 }),
  customer_annual_revenue: varchar("customer_annual_revenue", { length: 20 }),
  customer_ownership: varchar("customer_ownership", { length: 30 }),
  customer_hq_country: varchar("customer_hq_country", { length: 60 }),
  customer_operating_regions: jsonb("customer_operating_regions"),
  customer_certifications: jsonb("customer_certifications"),
  customer_regulators: jsonb("customer_regulators"),
  customer_public_incident: varchar("customer_public_incident", { length: 30 }),
  customer_cloud_provider: varchar("customer_cloud_provider", { length: 30 }),
  customer_identity_provider: varchar("customer_identity_provider", { length: 30 }),
  customer_scm_platform: varchar("customer_scm_platform", { length: 30 }),
  customer_incumbent_ai_tooling: jsonb("customer_incumbent_ai_tooling"),
  likely_integration_systems: jsonb("likely_integration_systems"),
  customer_ai_maturity_evidence: jsonb("customer_ai_maturity_evidence"),
  customer_ai_leadership: varchar("customer_ai_leadership", { length: 40 }),
  customer_public_ai_policy: varchar("customer_public_ai_policy", { length: 40 }),
  opportunity_type: varchar("opportunity_type", { length: 40 }),
  target_user_function: jsonb("target_user_function"),
  estimated_users_in_scope: varchar("estimated_users_in_scope", { length: 20 }),
  competitors: jsonb("competitors"),
  build_vs_buy_signal: varchar("build_vs_buy_signal", { length: 80 }),
  key_advantages_rows: jsonb("key_advantages_rows"),
  information_basis: jsonb("information_basis"),
  answer_confidence: varchar("answer_confidence", { length: 80 }),
  research_date: date("research_date"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
