import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
  integer,
} from "drizzle-orm/pg-core";

/** Aligned with Excel "buyer_cots" sheet (column order matches nested sheet). */
export const cotsBuyerAssessments = pgTable("cots_buyer_assessments", {
  id: uuid("id").defaultRandom().primaryKey(),
  buyer_cots_id: uuid("buyer_cots_id").unique().defaultRandom(),
  user_id: integer("user_id"),
  organization_id: varchar("organization_id", { length: 255 }),
  organization_name: varchar("organization_name", { length: 255 }),
  industry: varchar("industry", { length: 200 }),
  industry_sector: varchar("industry_sector", { length: 200 }),
  employee_count: varchar("employee_count", { length: 100 }),
  geographic_regions: jsonb("geographic_regions"),
  pain_point: text("pain_point"),
  business_outcomes: varchar("business_outcomes", { length: 300 }),
  business_unit: varchar("business_unit", { length: 100 }),
  budget_range: varchar("budget_range", { length: 100 }),
  target_timeline: varchar("target_timeline", { length: 100 }),
  critical_of_ai_solution: varchar("critical_of_ai_solution", { length: 100 }),
  vendor_name: varchar("vendor_name", { length: 200 }),
  specific_product: varchar("specific_product", { length: 200 }),
  gap_requirement_product: text("gap_requirement_product"),
  integrate_system: jsonb("integrate_system"),
  integrate_system_other: varchar("integrate_system_other", { length: 300 }),
  current_tech_stack: jsonb("current_tech_stack"),
  digital_maturity: varchar("digital_maturity", { length: 100 }),
  governance_maturity: varchar("governance_maturity", { length: 100 }),
  ai_governance_board: varchar("ai_governance_board", { length: 100 }),
  ai_ethics_policy: varchar("ai_ethics_policy", { length: 100 }),
  team_composition: jsonb("team_composition"),
  data_sensitivity_level: varchar("data_sensitivity_level", { length: 100 }),
  regulatory_requirments: jsonb("regulatory_requirments"),
  risk_appetite: varchar("risk_appetite", { length: 100 }),
  statke_at_ai_decisions: varchar("statke_at_ai_decisions", { length: 100 }),
  impact_by_ai: jsonb("impact_by_ai"),
  vendor_capabilities: varchar("vendor_capabilities", { length: 100 }),
  vendor_security_posture: varchar("vendor_security_posture", { length: 100 }),
  vendor_compliance_certifications: jsonb("vendor_compliance_certifications"),
  phased_rollout_plan: varchar("phased_rollout_plan", { length: 100 }),
  rollback_capability: varchar("rollback_capability", { length: 100 }),
  management_plan: varchar("management_plan", { length: 100 }),
  compliance_document: text("compliance_document"),
  vendor_usage_data: varchar("vendor_usage_data", { length: 100 }),
  audit_logs: varchar("audit_logs", { length: 100 }),
  testing_results: varchar("testing_results", { length: 100 }),
  identified_risks: text("identified_risks"),
  risk_domain_scores: text("risk_domain_scores"),
  contextual_multipliers: text("contextual_multipliers"),
  buyer_risk_mitigation: text("buyer_risk_mitigation"),
  assessment_id: uuid("assessment_id").notNull(),
  risk_mitigation_mapping_ids: jsonb("risk_mitigation_mapping_ids"),
  /** Generated on submit: full Vendor Risk Assessment Report (buyer + attestation). */
  vendor_risk_assessment_report: jsonb("vendor_risk_assessment_report"),
  /** Set when assessment expires: frozen JSON; live vendor_risk_assessment_report is cleared. */
  archived_vendor_risk_assessment_report: jsonb("archived_vendor_risk_assessment_report"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
