import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";

export const customAiAssessments = pgTable("custom_ai_assessments", {
  id: uuid("id").defaultRandom().primaryKey(),
  assessment_id: uuid("assessment_id").notNull(),
  business_pain_point: text("business_pain_point"),
  expected_outcomes: varchar("expected_outcomes", { length: 300 }),
  owning_department: varchar("owning_department", { length: 100 }),
  target_timeline: varchar("target_timeline", { length: 100 }),
  criticality: varchar("criticality", { length: 100 }),
  build_rationale: text("build_rationale"),
  development_platform: jsonb("development_platform"),
  ml_frameworks: jsonb("ml_frameworks"),
  ai_model_types: jsonb("ai_model_types"),
  customization_level: varchar("customization_level", { length: 100 }),
  development_stage: varchar("development_stage", { length: 100 }),
  training_data_source: jsonb("training_data_source"),
  training_data_volume: varchar("training_data_volume", { length: 100 }),
  training_data_quality: varchar("training_data_quality", { length: 100 }),
  training_data_biases: varchar("training_data_biases", { length: 100 }),
  data_labeling_process: varchar("data_labeling_process", { length: 100 }),
  bias_testing_plan: jsonb("bias_testing_plan"),
  adversarial_testing: varchar("adversarial_testing", { length: 100 }),
  interpretability_approach: varchar("interpretability_approach", { length: 100 }),
  human_oversight: jsonb("human_oversight"),
  decision_autonomy: varchar("decision_autonomy", { length: 100 }),
  continuous_learning: varchar("continuous_learning", { length: 100 }),
  ai_governance_board: varchar("ai_governance_board", { length: 100 }),
  ai_ethics_policy: varchar("ai_ethics_policy", { length: 100 }),
  executive_sponsorship: varchar("executive_sponsorship", { length: 100 }),
  team_composition: jsonb("team_composition"),
  development_budget: varchar("development_budget", { length: 100 }),
  hosting_type: varchar("hosting_type", { length: 100 }),
  deployment_options: jsonb("deployment_options"),
  data_residency: jsonb("data_residency"),
  model_version_control: varchar("model_version_control", { length: 100 }),
  rollback_procedures: varchar("rollback_procedures", { length: 100 }),
  data_sensitivity: varchar("data_sensitivity", { length: 100 }),
  regulatory_requirements: jsonb("regulatory_requirements"),
  risk_appetite: varchar("risk_appetite", { length: 100 }),
  decision_stakes: varchar("decision_stakes", { length: 100 }),
  validation_approach: varchar("validation_approach", { length: 100 }),
  identified_risks: text("identified_risks"),
  risk_domain_scores: text("risk_domain_scores"),
  contextual_multipliers: text("contextual_multipliers"),
  risk_mitigation: text("risk_mitigation"),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
