import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
  integer,
  boolean,
  numeric,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/** Aligned with Excel "vendor_self_attestation" sheet (column order matches nested sheet). */
export const vendorSelfAttestations = pgTable("vendor_self_attestations", {
  id: uuid("id").defaultRandom().primaryKey(),
  vendor_self_attestation_id: uuid("vendor_self_attestation_id").unique().defaultRandom(),
  user_id: integer("user_id"),
  organization_id: varchar("organization_id", { length: 255 }),
  vendor_type: varchar("vendor_type", { length: 100 }),
  target_industries: jsonb("target_industries"),
  company_stage: varchar("company_stage", { length: 100 }),
  company_website: text("company_website"),
  company_description: text("company_description"),
  no_of_employees: varchar("no_of_employees", { length: 100 }),
  year_founded: integer("year_founded"),
  headquarter_location: varchar("headquarter_location", { length: 255 }),
  operate_regions: jsonb("operate_regions"),
  funding_status: varchar("funding_status", { length: 50 }),
  financial_position: varchar("financial_position", { length: 50 }),
  enterprise_customers: integer("enterprise_customers"),
  customer_retention_rate: numeric("customer_retention_rate", { precision: 5, scale: 2 }),
  trust_centre_url: varchar("trust_centre_url", { length: 500 }),
  has_public_security_incident: varchar("has_public_security_incident", { length: 10 }),
  security_incidents: jsonb("security_incidents").default(sql`'[]'::jsonb`).notNull(),
  product_name: varchar("product_name", { length: 255 }),
  market_product_material: text("market_product_material"),
  tech_product_specifications: text("tech_product_specifications"),
  regulatorycompliance_cert_material: text("regulatorycompliance_cert_material"),
  purchase_decisions_by: jsonb("purchase_decisions_by"),
  pain_points: text("pain_points"),
  alternatives_consider: text("alternatives_consider"),
  unique_solution: text("unique_solution"),
  roi_value_metrics: text("roi_value_metrics"),
  product_capabilities: jsonb("product_capabilities"),
  ai_models_usage: jsonb("ai_models_usage"),
  ai_model_transparency: varchar("ai_model_transparency", { length: 100 }),
  ai_autonomy_level: varchar("ai_autonomy_level", { length: 100 }),
  /** Yes / No — documented AI governance policy (AI Technical Capabilities); uploads in document_uploads.aiGovernancePolicy */
  documented_ai_governance_policy: varchar("documented_ai_governance_policy", { length: 100 }),
  security_compliance_certificates: jsonb("security_compliance_certificates"),
  assessment_feedback: varchar("assessment_feedback", { length: 100 }),
  audit_frequency: varchar("audit_frequency", { length: 100 }),
  /** Yes / No — vendor offers a HIPAA Business Associate Agreement */
  hipaa_baa: varchar("hipaa_baa", { length: 100 }),
  /** { status, level, boundary, marketplace_id, authorized_at } */
  fedramp_authorization: jsonb("fedramp_authorization"),
  pii_information: varchar("pii_information", { length: 100 }),
  data_residency_options: jsonb("data_residency_options"),
  data_retention_policy: text("data_retention_policy"),
  bias_ai: jsonb("bias_ai"),
  security_testing: varchar("security_testing", { length: 100 }),
  human_oversight: jsonb("human_oversight"),
  training_data_document: varchar("training_data_document", { length: 100 }),
  sla_guarantee: varchar("sla_guarantee", { length: 100 }),
  support_slas: text("support_slas"),
  change_management: text("change_management"),
  incident_response_plan: varchar("incident_response_plan", { length: 100 }),
  production_model_monitoring: varchar("production_model_monitoring", { length: 50 }),
  critical_incident_response_target: varchar("critical_incident_response_target", { length: 30 }),
  critical_incident_resolution_target: varchar("critical_incident_resolution_target", { length: 30 }),
  ir_plan_test_frequency: varchar("ir_plan_test_frequency", { length: 30 }),
  incident_customer_communication: varchar("incident_customer_communication", { length: 30 }),
  support_coverage: varchar("support_coverage", { length: 40 }),
  account_management: varchar("account_management", { length: 40 }),
  versions_models: boolean("versions_models"),
  model_versioning_method: varchar("model_versioning_method", { length: 50 }),
  privacy_programme_scope: varchar("privacy_programme_scope", { length: 50 }),
  typical_data_volume: varchar("typical_data_volume", { length: 30 }),
  ai_ethics_governance_maturity: varchar("ai_ethics_governance_maturity", { length: 50 }),
  is_multi_tenant: boolean("is_multi_tenant"),
  tenant_isolation_model: varchar("tenant_isolation_model", { length: 50 }),
  deployment_customization: varchar("deployment_customization", { length: 40 }),
  integration_complexity: varchar("integration_complexity", { length: 40 }),
  encryption_at_rest: varchar("encryption_at_rest", { length: 50 }),
  encryption_at_rest_evidence_id: varchar("encryption_at_rest_evidence_id", { length: 255 }),
  tls_in_transit: varchar("tls_in_transit", { length: 50 }),
  data_subject_rights: jsonb("data_subject_rights").default(sql`'[]'::jsonb`).notNull(),
  controller_or_processor: varchar("controller_or_processor", { length: 20 }),
  sub_processors: jsonb("sub_processors").default(sql`'[]'::jsonb`).notNull(),
  vulnerability_disclosure_policy: jsonb("vulnerability_disclosure_policy"),
  bug_bounty: jsonb("bug_bounty"),
  independent_pen_test_frequency: varchar("independent_pen_test_frequency", { length: 30 }),
  dpa_available: varchar("dpa_available", { length: 30 }),
  dpa_url: varchar("dpa_url", { length: 500 }),
  rollback_deployment_issues: varchar("rollback_deployment_issues", { length: 100 }),
  solution_hosted: jsonb("solution_hosted"),
  deployment_scale: varchar("deployment_scale", { length: 100 }),
  stage_product: varchar("stage_product", { length: 100 }),
  test_policy_document: varchar("test_policy_document", { length: 100 }),
  available_usage_data: varchar("available_usage_data", { length: 100 }),
  audit_logs: varchar("audit_logs", { length: 100 }),
  test_results: varchar("test_results", { length: 100 }),
  assessment_id: uuid("assessment_id"),
  document_uploads: jsonb("document_uploads"),
  /** Parsed expiry per compliance upload file (fileName -> { category, expiryAt, parsedAt, error? }). */
  compliance_document_expiries: jsonb("compliance_document_expiries"),
  /** Aggregated framework mapping rows for reports (from compliance PDF parse). */
  framework_mapping_rows: jsonb("framework_mapping_rows"),
  status: varchar("status", { length: 20 }).default("DRAFT"),
  visible_to_buyer: boolean("visible_to_buyer").default(false),
  visible_ai_governance: boolean("visible_ai_governance").default(false),
  visible_security_posture: boolean("visible_security_posture").default(false),
  visible_data_privacy: boolean("visible_data_privacy").default(false),
  visible_compliance: boolean("visible_compliance").default(false),
  visible_model_risk: boolean("visible_model_risk").default(false),
  visible_data_practices: boolean("visible_data_practices").default(false),
  visible_compliance_certifications: boolean("visible_compliance_certifications").default(false),
  visible_operations_support: boolean("visible_operations_support").default(false),
  visible_vendor_management: boolean("visible_vendor_management").default(false),
  /** Product Profile detail: Company identity / Company reach blocks visible to buyers. */
  visible_company_identity: boolean("visible_company_identity").default(false),
  visible_company_reach: boolean("visible_company_reach").default(false),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  /** Set when status first becomes COMPLETED; never updated by visibility toggles. */
  submitted_at: timestamp("submitted_at", { withTimezone: true }),
  /** Expiry date: 3 months from created_at (set by DB trigger on insert; backfilled by migration). */
  expiry_at: timestamp("expiry_at", { withTimezone: true }),
  /** User moved a completed (non–time-expired) attestation to the Archived tab; cleared on reactive. */
  user_archived_at: timestamp("user_archived_at", { withTimezone: true }),
  /** Generated product profile report (trust score + sections) when attestation is submitted as COMPLETED. */
  generated_profile_report: jsonb("generated_profile_report"),
  /** Latest VTS from most recent generated_profile_reports row. */
  latest_trust_score: integer("latest_trust_score"),
  latest_trust_grade: varchar("latest_trust_grade", { length: 8 }),
  latest_profile_report_id: uuid("latest_profile_report_id"),
  /** Controls LLM used for the latest generated VTS / profile report. */
  llm_model_id: varchar("llm_model_id", { length: 512 }),
  llm_model_label: varchar("llm_model_label", { length: 512 }),
});
