-- Buyer COTS field spec V2 / v4: widen outcomes and add audited fields.
ALTER TABLE public.cots_buyer_assessments
  ALTER COLUMN business_outcomes TYPE text;

ALTER TABLE public.cots_buyer_assessments
  ADD COLUMN IF NOT EXISTS use_case_types jsonb,
  ADD COLUMN IF NOT EXISTS users_in_scope varchar(20),
  ADD COLUMN IF NOT EXISTS current_usage_state varchar(80),
  ADD COLUMN IF NOT EXISTS pilot_status varchar(80),
  ADD COLUMN IF NOT EXISTS accountable_owner_name varchar(200),
  ADD COLUMN IF NOT EXISTS accountable_owner_role varchar(40),
  ADD COLUMN IF NOT EXISTS data_classes jsonb,
  ADD COLUMN IF NOT EXISTS data_subject_jurisdictions jsonb,
  ADD COLUMN IF NOT EXISTS decision_domains jsonb,
  ADD COLUMN IF NOT EXISTS output_exposure varchar(80),
  ADD COLUMN IF NOT EXISTS regulatory_requirements_derived jsonb,
  ADD COLUMN IF NOT EXISTS regulatory_requirements_added jsonb,
  ADD COLUMN IF NOT EXISTS regulatory_requirements_removed jsonb,
  ADD COLUMN IF NOT EXISTS retention_requirement varchar(30),
  ADD COLUMN IF NOT EXISTS training_use_of_data varchar(80),
  ADD COLUMN IF NOT EXISTS training_use_of_data_stance varchar(20),
  ADD COLUMN IF NOT EXISTS training_use_of_data_dispute_note text,
  ADD COLUMN IF NOT EXISTS human_review_level varchar(80),
  ADD COLUMN IF NOT EXISTS ai_disclosure varchar(40),
  ADD COLUMN IF NOT EXISTS deployment_model varchar(80),
  ADD COLUMN IF NOT EXISTS cloud_provider jsonb,
  ADD COLUMN IF NOT EXISTS integration_access_levels jsonb,
  ADD COLUMN IF NOT EXISTS implementation_capacity varchar(80),
  ADD COLUMN IF NOT EXISTS training_effort varchar(80),
  ADD COLUMN IF NOT EXISTS vendor_evidence_received jsonb,
  ADD COLUMN IF NOT EXISTS monitoring_data_stance varchar(20),
  ADD COLUMN IF NOT EXISTS monitoring_data_dispute_note text,
  ADD COLUMN IF NOT EXISTS audit_logs_stance varchar(20),
  ADD COLUMN IF NOT EXISTS audit_logs_dispute_note text,
  ADD COLUMN IF NOT EXISTS data_export_capability varchar(80),
  ADD COLUMN IF NOT EXISTS data_export_stance varchar(20),
  ADD COLUMN IF NOT EXISTS data_export_dispute_note text,
  ADD COLUMN IF NOT EXISTS unavailability_impact varchar(80),
  ADD COLUMN IF NOT EXISTS contracts_in_place jsonb,
  ADD COLUMN IF NOT EXISTS contract_notice_period varchar(30),
  ADD COLUMN IF NOT EXISTS assessor_name varchar(200),
  ADD COLUMN IF NOT EXISTS assessor_role varchar(40),
  ADD COLUMN IF NOT EXISTS answer_confidence varchar(80),
  ADD COLUMN IF NOT EXISTS review_due_date timestamptz,
  ADD COLUMN IF NOT EXISTS unlinked_vendor varchar(10),
  ADD COLUMN IF NOT EXISTS target_outcome_metric varchar(120),
  ADD COLUMN IF NOT EXISTS target_outcome_baseline varchar(80),
  ADD COLUMN IF NOT EXISTS target_outcome_target varchar(80);
