import { pgTable, uuid, varchar, text, timestamp, jsonb, integer, boolean, } from "drizzle-orm/pg-core";
/** Aligned with Excel "vendor_self_attestation" sheet (column order matches nested sheet). */
export const vendorSelfAttestations = pgTable("vendor_self_attestations", {
    id: uuid("id").defaultRandom().primaryKey(),
    vendor_self_attestation_id: uuid("vendor_self_attestation_id").unique().defaultRandom(),
    user_id: integer("user_id"),
    organization_id: varchar("organization_id", { length: 255 }),
    vendor_type: varchar("vendor_type", { length: 100 }),
    target_industries: jsonb("target_industries"),
    company_stage: varchar("company_stage", { length: 100 }),
    company_website: varchar("company_website", { length: 500 }),
    company_description: text("company_description"),
    no_of_employees: varchar("no_of_employees", { length: 100 }),
    year_founded: integer("year_founded"),
    headquarter_location: varchar("headquarter_location", { length: 255 }),
    operate_regions: jsonb("operate_regions"),
    product_name: varchar("product_name", { length: 255 }),
    market_product_material: text("market_product_material"),
    tech_product_specifications: text("tech_product_specifications"),
    regulatorycompliance_cert_material: text("regulatorycompliance_cert_material"),
    purchase_decisions_by: jsonb("purchase_decisions_by"),
    pain_points: text("pain_points"),
    alternatives_consider: text("alternatives_consider"),
    unique_solution: text("unique_solution"),
    roi_value_metrics: varchar("roi_value_metrics", { length: 500 }),
    product_capabilities: jsonb("product_capabilities"),
    ai_models_usage: jsonb("ai_models_usage"),
    ai_model_transparency: varchar("ai_model_transparency", { length: 100 }),
    ai_autonomy_level: varchar("ai_autonomy_level", { length: 100 }),
    /** Yes / No — documented AI governance policy (AI Technical Capabilities); uploads in document_uploads.aiGovernancePolicy */
    documented_ai_governance_policy: varchar("documented_ai_governance_policy", { length: 100 }),
    security_compliance_certificates: jsonb("security_compliance_certificates"),
    assessment_feedback: varchar("assessment_feedback", { length: 100 }),
    audit_frequency: varchar("audit_frequency", { length: 100 }),
    pii_information: varchar("pii_information", { length: 100 }),
    data_residency_options: jsonb("data_residency_options"),
    data_retention_policy: text("data_retention_policy"),
    bias_ai: jsonb("bias_ai"),
    security_testing: varchar("security_testing", { length: 100 }),
    human_oversight: jsonb("human_oversight"),
    training_data_document: varchar("training_data_document", { length: 100 }),
    sla_guarantee: varchar("sla_guarantee", { length: 100 }),
    support_slas: text("support_slas"),
    change_management: text("change_management"),
    incident_response_plan: varchar("incident_response_plan", { length: 100 }),
    rollback_deployment_issues: varchar("rollback_deployment_issues", { length: 100 }),
    solution_hosted: jsonb("solution_hosted"),
    deployment_scale: varchar("deployment_scale", { length: 100 }),
    stage_product: varchar("stage_product", { length: 100 }),
    test_policy_document: varchar("test_policy_document", { length: 100 }),
    available_usage_data: varchar("available_usage_data", { length: 100 }),
    audit_logs: varchar("audit_logs", { length: 100 }),
    test_results: varchar("test_results", { length: 100 }),
    assessment_id: uuid("assessment_id"),
    document_uploads: jsonb("document_uploads"),
    /** Parsed expiry per compliance upload file (fileName -> { category, expiryAt, parsedAt, error? }). */
    compliance_document_expiries: jsonb("compliance_document_expiries"),
    /** Aggregated framework mapping rows for reports (from compliance PDF parse). */
    framework_mapping_rows: jsonb("framework_mapping_rows"),
    status: varchar("status", { length: 20 }).default("DRAFT"),
    visible_to_buyer: boolean("visible_to_buyer").default(false),
    visible_ai_governance: boolean("visible_ai_governance").default(false),
    visible_security_posture: boolean("visible_security_posture").default(false),
    visible_data_privacy: boolean("visible_data_privacy").default(false),
    visible_compliance: boolean("visible_compliance").default(false),
    visible_model_risk: boolean("visible_model_risk").default(false),
    visible_data_practices: boolean("visible_data_practices").default(false),
    visible_compliance_certifications: boolean("visible_compliance_certifications").default(false),
    visible_operations_support: boolean("visible_operations_support").default(false),
    visible_vendor_management: boolean("visible_vendor_management").default(false),
    /** Product Profile detail: Company identity / Company reach blocks visible to buyers. */
    visible_company_identity: boolean("visible_company_identity").default(false),
    visible_company_reach: boolean("visible_company_reach").default(false),
    created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    /** Set when status first becomes COMPLETED; never updated by visibility toggles. */
    submitted_at: timestamp("submitted_at", { withTimezone: true }),
    /** Expiry date: 3 months from created_at (set by DB trigger on insert; backfilled by migration). */
    expiry_at: timestamp("expiry_at", { withTimezone: true }),
    /** User moved a completed (non–time-expired) attestation to the Archived tab; cleared on reactive. */
    user_archived_at: timestamp("user_archived_at", { withTimezone: true }),
    /** Generated product profile report (trust score + sections) when attestation is submitted as COMPLETED. */
    generated_profile_report: jsonb("generated_profile_report"),
});
