import express from "express";
import authenticateToken from "../middlewares/routesProtection.js";
import submitBuyerCotsAssessment from "../controllers/buyercots/submitBuyerCots.controller.js";
import saveBuyerCotsDraft from "../controllers/buyercots/saveBuyerCotsDraft.controller.js";
import getBuyerCotsById from "../controllers/assessments/getBuyerCotsById.controller.js";
import getBuyerRiskMappingsByAssessment from "../controllers/assessments/getBuyerRiskMappingsByAssessment.controller.js";
import getBuyerVendorRiskReport from "../controllers/assessments/getBuyerVendorRiskReport.controller.js";
import listBuyerVendorRiskReports from "../controllers/assessments/listBuyerVendorRiskReports.controller.js";
import deleteAssessment from "../controllers/assessments/deleteAssessment.controller.js";
import submitVendorCotsAssessment from "../controllers/vendorcots/submitVendorCots.controller.js";
import saveVendorCotsDraft from "../controllers/vendorcots/saveVendorCotsDraft.controller.js";
import getVendorCotsById from "../controllers/assessments/getVendorCotsById.controller.js";
import getBuyerCotsAutoGenerated from "../controllers/assessments/getBuyerCotsAutoGenerated.controller.js";
import listAssessmentsByOrganization from "../controllers/assessments/listAssessmentsByOrganization.controller.js";
import patchAssessmentUserArchive from "../controllers/assessments/patchAssessmentUserArchive.controller.js";
import listCustomerRiskReports from "../controllers/assessments/listCustomerRiskReports.controller.js";
import getCustomerRiskReportById from "../controllers/assessments/getCustomerRiskReportById.controller.js";
import deleteCustomerRiskReport from "../controllers/assessments/deleteCustomerRiskReport.controller.js";
import executiveStakeholderBrief from "../controllers/vendorReports/executiveStakeholderBrief.controller.js";
import salesQualificationReport from "../controllers/vendorReports/salesQualificationReport.controller.js";
import customerRiskMitigationPlan from "../controllers/vendorReports/customerRiskMitigationPlan.controller.js";
import implementationRoadmapProposal from "../controllers/vendorReports/implementationRoadmapProposal.controller.js";
import vendorComparisonMatrixReport from "../controllers/buyerReports/vendorComparisonMatrixReport.controller.js";
import complianceRiskSummaryReport from "../controllers/buyerReports/complianceRiskSummaryReport.controller.js";
import implementationRiskAssessmentReport from "../controllers/buyerReports/implementationRiskAssessmentReport.controller.js";
import mitigationActionPlanReport from "../controllers/buyerReports/mitigationActionPlanReport.controller.js";
import listGeneralReports from "../controllers/assessments/listGeneralReports.controller.js";
import getGeneralReportById from "../controllers/assessments/getGeneralReportById.controller.js";
import salesEnablement from "../controllers/assessments/salesEnablement.controller.js";
import salesAgentChat from "../controllers/assessments/salesAgentChat.controller.js";

const assessmentRouter = express.Router();

assessmentRouter
.get("/assessments", authenticateToken, listAssessmentsByOrganization)
.patch("/assessments/:id/user-archive", authenticateToken, patchAssessmentUserArchive)
.get("/buyerVendorRiskReports", authenticateToken, listBuyerVendorRiskReports)
.get("/customerRiskReports", authenticateToken, listCustomerRiskReports)
.get("/customerRiskReports/:id", authenticateToken, getCustomerRiskReportById)
.delete("/customerRiskReports/:id", authenticateToken, deleteCustomerRiskReport)
.get("/generalReports", authenticateToken, listGeneralReports)
.get("/generalReports/:id", authenticateToken, getGeneralReportById)
.post("/executiveStakeholderBrief", authenticateToken, executiveStakeholderBrief)
.post("/salesEnablement/chat", authenticateToken, salesAgentChat)
.post("/salesEnablement", authenticateToken, salesEnablement)
.post("/salesQualificationReport", authenticateToken, salesQualificationReport)
.post("/customerRiskMitigationPlan", authenticateToken, customerRiskMitigationPlan)
.post("/implementationRoadmapProposal", authenticateToken, implementationRoadmapProposal)
.post("/vendorComparisonMatrixReport", authenticateToken, vendorComparisonMatrixReport)
.post("/complianceRiskSummaryReport", authenticateToken, complianceRiskSummaryReport)
.post("/implementationRiskAssessmentReport", authenticateToken, implementationRiskAssessmentReport)
.post("/mitigationActionPlanReport", authenticateToken, mitigationActionPlanReport)
.get("/buyerCotsAssessment/:id/vendor-risk-report", authenticateToken, getBuyerVendorRiskReport)
.get("/buyerCotsAssessment/:id/risk-mappings", authenticateToken, getBuyerRiskMappingsByAssessment)
.get("/buyerCotsAssessment/:id", authenticateToken, getBuyerCotsById)
.get("/vendorCotsAssessment/:id", authenticateToken, getVendorCotsById)
.post("/buyerCotsAssessment/autoGenerated", authenticateToken, getBuyerCotsAutoGenerated)
.post("/buyerCotsAssessment/save-draft", authenticateToken, saveBuyerCotsDraft)
.post("/buyerCotsAssessment", authenticateToken, submitBuyerCotsAssessment)
.post("/vendorCotsAssessment/save-draft", authenticateToken, saveVendorCotsDraft)
.post("/vendorCotsAssessment", authenticateToken, submitVendorCotsAssessment)
.delete("/assessments/:id", authenticateToken, deleteAssessment);


export default assessmentRouter;
