/** Maps step section + field index to API payload key (camelCase) for Buyer COTS Assessment */
export const BUYER_COTS_FIELD_KEYS = {
  organizationProfile: ["organizationName", "industrySector", "employeeCount", "operatingRegions"] as const,
  useCase: ["businessPainPoint", "expectedOutcomes", "owningDepartment", "budgetRange", "targetTimeline", "criticality"] as const,
  vendorEvaluation: ["vendorName", "productName", "requirementGaps", "integrationSystems", "techStack"] as const,
  readiness: ["digitalMaturityLevel", "dataGovernanceMaturity", "aiGovernanceBoard", "aiEthicsPolicy", "implementationTeamComposition"] as const,
  riskProfile: ["dataSensitivity", "regulatoryRequirements", "riskAppetite", "decisionStakes", "impactedStakeholders"] as const,
  vendorRisk: ["vendorValidationApproach", "vendorSecurityPosture", "vendorCertifications"] as const,
  implementation: ["pilotRolloutPlan", "rollbackCapability", "changeManagementPlan"] as const,
  evidence: ["vendorComplianceDocumentation", "monitoringDataAvailable", "auditLogsAvailable", "testingResultsAvailable"] as const,
  autoGenerated: ["identifiedRisks", "riskDomainScores", "contextualMultipliers", "riskMitigation"] as const,
} as const;

const allKeys = [
  ...BUYER_COTS_FIELD_KEYS.organizationProfile,
  ...BUYER_COTS_FIELD_KEYS.useCase,
  ...BUYER_COTS_FIELD_KEYS.vendorEvaluation,
  ...BUYER_COTS_FIELD_KEYS.readiness,
  ...BUYER_COTS_FIELD_KEYS.riskProfile,
  ...BUYER_COTS_FIELD_KEYS.vendorRisk,
  ...BUYER_COTS_FIELD_KEYS.implementation,
  ...BUYER_COTS_FIELD_KEYS.evidence,
  ...BUYER_COTS_FIELD_KEYS.autoGenerated,
] as const;

export const BUYER_COTS_INITIAL_STATE: Record<string, string> = Object.fromEntries(
  allKeys.map((k) => [k, ""])
);
