import { BUYER_COTS_FORM_SECTIONS } from "./buyerCotsFormSchema";
import { getBuyerCotsFieldOptions } from "./buyerCotsOptions";

function sectionToIndexed(sectionId: string) {
  const section = BUYER_COTS_FORM_SECTIONS.find((s) => s.id === sectionId);
  const out: Record<
    number,
    {
      label: string;
      placeholder: string;
      required: string;
      options?: { label: string; value: string }[];
      multiselect?: boolean;
    }
  > = {};
  if (!section) return out;
  section.fields.forEach((field, i) => {
    out[i] = {
      label: field.label,
      placeholder: field.placeholder,
      required: field.required ? "true" : "false",
      options: field.optionsKey ? getBuyerCotsFieldOptions(field.optionsKey) : undefined,
      multiselect: field.inputType === "multiselect" || field.inputType === "integrationAccess",
    };
  });
  return out;
}

export const BUYER_COTS_ASSESSMENT = {
  context: sectionToIndexed("context"),
  purchase: sectionToIndexed("purchase"),
  dataLegal: sectionToIndexed("dataLegal"),
  oversight: sectionToIndexed("oversight"),
  environment: sectionToIndexed("environment"),
  vendorTrust: sectionToIndexed("vendorTrust"),
  exit: sectionToIndexed("exit"),
  provenance: sectionToIndexed("provenance"),
  organizationProfile: sectionToIndexed("context"),
  useCase: sectionToIndexed("purchase"),
  vendorEvaluation: sectionToIndexed("purchase"),
  readiness: sectionToIndexed("oversight"),
  riskProfile: sectionToIndexed("dataLegal"),
  vendorRisk: sectionToIndexed("vendorTrust"),
  implementation: sectionToIndexed("exit"),
  evidence: sectionToIndexed("vendorTrust"),
  autoGenerated: {
    0: {
      label: "Identified Risks",
      placeholder: "Shows list of Risk IDs and titles applicable to your use case",
    },
    1: {
      label: "Risk Domain Scores",
      placeholder: "Shows risk scores by domain",
    },
    2: {
      label: "Contextual Multipliers",
      placeholder: "Shows multipliers applied",
    },
    3: {
      label: "Buyer Risk Mitigation",
      placeholder: "Auto-recommended mitigation tactics",
    },
  },
};
