/** Maps step section to API payload keys (camelCase) for Vendor COTS Assessment */
export const VENDOR_COTS_FIELD_KEYS = {
  customerDiscovery: [
    "customerOrganizationName",
    "customerSector",
    "primaryPainPoint",
    "expectedOutcomes",
    "customerBudgetRange",
    "implementationTimeline",
  ] as const,
  solutionFit: [
    "selectedProductId",
    "productFeatures",
    "implementationApproach",
    "customizationLevel",
    "integrationComplexity",
  ] as const,
  customerRiskContext: [
    "regulatoryRequirements",
    "regulatoryRequirementsOther",
    "dataSensitivity",
    "customerRiskTolerance",
  ] as const,
  competitiveAnalysis: ["alternativesConsidered", "keyAdvantages"] as const,
  customerRiskMitigation: [
    "customerSpecificRisks",
    "customerSpecificRisksOther",
  ] as const,
  autoGenerated: [
    "identifiedRisks",
    "riskDomainScores",
    "contextualMultipliers",
    "riskMitigation",
  ] as const,
} as const;

const allKeys = [
  ...VENDOR_COTS_FIELD_KEYS.customerDiscovery,
  ...VENDOR_COTS_FIELD_KEYS.solutionFit,
  ...VENDOR_COTS_FIELD_KEYS.customerRiskContext,
  ...VENDOR_COTS_FIELD_KEYS.competitiveAnalysis,
  ...VENDOR_COTS_FIELD_KEYS.customerRiskMitigation,
  ...VENDOR_COTS_FIELD_KEYS.autoGenerated,
] as const;

export const VENDOR_COTS_INITIAL_STATE: Record<string, string> = Object.fromEntries(
  allKeys.map((k) => [k, ""])
);
