/** Maps step section to API payload keys (camelCase) for Vendor COTS Assessment */
export const VENDOR_COTS_FIELD_KEYS = {
  customerDiscovery: [
    "customerOrganizationName",
    "customerSector",
    "primaryPainPoint",
    "expectedOutcomes",
    "customerBudgetRange",
    "implementationTimeline",
  ] as const,
  customerProfile: [
    "customerEmployeeCount",
    "customerEngHeadcount",
    "customerAnnualRevenue",
    "customerOwnership",
    "customerHqCountry",
    "customerOperatingRegions",
  ] as const,
  solutionFit: [
    "selectedProductId",
    "productFeatures",
    "implementationApproach",
    "customizationLevel",
  ] as const,
  customerRiskContext: [
    "regulatoryRequirements",
    "regulatoryRequirementsOther",
    "dataSensitivity",
    "customerRiskTolerance",
  ] as const,
  compliancePosture: [
    "customerCertifications",
    "customerRegulators",
    "customerPublicIncident",
  ] as const,
  technologySignals: [
    "customerCloudProvider",
    "customerIdentityProvider",
    "customerScmPlatform",
    "customerIncumbentAiTooling",
    "likelyIntegrationSystems",
  ] as const,
  aiMaturity: [
    "customerAiMaturityEvidence",
    "customerAiLeadership",
    "customerPublicAiPolicy",
  ] as const,
  competitiveAnalysis: [
    "opportunityType",
    "targetUserFunction",
    "estimatedUsersInScope",
    "competitors",
    "buildVsBuySignal",
    "keyAdvantagesRows",
  ] as const,
  customerRiskMitigation: [
    "customerSpecificRisks",
    "customerSpecificRisksOther",
  ] as const,
  provenance: [
    "informationBasis",
    "answerConfidence",
    "researchDate",
  ] as const,
  autoGenerated: [
    "identifiedRisks",
    "riskDomainScores",
    "contextualMultipliers",
    "riskMitigation",
  ] as const,
} as const;

const allKeys = [
  ...VENDOR_COTS_FIELD_KEYS.customerDiscovery,
  ...VENDOR_COTS_FIELD_KEYS.customerProfile,
  ...VENDOR_COTS_FIELD_KEYS.solutionFit,
  ...VENDOR_COTS_FIELD_KEYS.customerRiskContext,
  ...VENDOR_COTS_FIELD_KEYS.compliancePosture,
  ...VENDOR_COTS_FIELD_KEYS.technologySignals,
  ...VENDOR_COTS_FIELD_KEYS.aiMaturity,
  ...VENDOR_COTS_FIELD_KEYS.competitiveAnalysis,
  ...VENDOR_COTS_FIELD_KEYS.customerRiskMitigation,
  ...VENDOR_COTS_FIELD_KEYS.provenance,
  ...VENDOR_COTS_FIELD_KEYS.autoGenerated,
] as const;

export const VENDOR_COTS_FORM_KEYS = allKeys.filter(
  (k) =>
    !(VENDOR_COTS_FIELD_KEYS.autoGenerated as readonly string[]).includes(k),
);

export const VENDOR_COTS_MULTISELECT_KEYS = [
  "productFeatures",
  "regulatoryRequirements",
  "customerSpecificRisks",
  "customerOperatingRegions",
  "customerCertifications",
  "customerRegulators",
  "customerIncumbentAiTooling",
  "likelyIntegrationSystems",
  "customerAiMaturityEvidence",
  "targetUserFunction",
  "informationBasis",
] as const;

export const VENDOR_COTS_REPEATER_KEYS = [
  "competitors",
  "keyAdvantagesRows",
] as const;

export const VENDOR_COTS_INITIAL_STATE: Record<string, string> = Object.fromEntries(
  allKeys.map((k) => {
    if (k === "competitors") {
      return [k, JSON.stringify([{ name: "", incumbent: "No", basis: "" }])];
    }
    if (k === "keyAdvantagesRows") {
      return [k, JSON.stringify([{ advantage: "", category: "" }])];
    }
    return [k, ""];
  }),
);
