import FormField from "../../../UI/FormField";
import HeaderForBuyer from "../../BuyerOnboarding/HeaderForBuyer";
import { BUYER_COTS_FIELD_KEYS } from "../../../../constants/buyerCotsAssessmentKeys";

const AutoGenerated = ({
  data,
  formData,
  readOnly = true,
  loading = false,
  title,
  subTitle,
  icon,
}) => {
  const keys = BUYER_COTS_FIELD_KEYS.autoGenerated;
  return (
    <>
      <HeaderForBuyer
        className="header_for_vendor"
        title_vendor={title ?? "Auto Generated"}
        sub_title_vendor={subTitle}
        icon={icon}
      />
      <div>
        {loading && (
          <p style={{ marginBottom: "1rem", color: "#666" }}>
            Loading auto-generated data...
          </p>
        )}
        {keys.map((key, i) => (
          <div key={key} className="form_fields_vendor buyer_cots_field">
            <FormField
              label={data[i].label}
              mandatory={data[i].required}
              tooltipText={data[i].helpText ?? data[i].placeholder}
            >
              <textarea
                rows={3}
                value={formData[key] ?? ""}
                readOnly={readOnly}
                placeholder={data[i].placeholder}
                style={
                  readOnly
                    ? {
                        backgroundColor: "#f5f5f5",
                        cursor: "not-allowed",
                        color: "#333",
                      }
                    : undefined
                }
                aria-label={data[i].label}
              />
            </FormField>
          </div>
        ))}
      </div>
    </>
  );
};

export default AutoGenerated;
