import "../../VendorOnboarding/vendor_onboarding.css";
import "../../BuyerOnboarding/buyer_onboarding.css";
import "../../VendorAttestations/vendor_attestation_preview.css";
import "../../UserManagement/user_management.css";
import "../../../../styles/card.css";
import CardContainerOnBoarding from "../../../UI/CardContainerOnBoarding";
import CardOnBoarding from "../../../UI/CardOnBoarding";
import MultiStepTabs from "../../../UI/MultiStepTabs";
import OrganizationProfile from "./OrganizationProfile";
import {
  BUYER_COTS_INITIAL_STATE,
  BUYER_COTS_FIELD_KEYS,
} from "../../../../constants/buyerCotsAssessmentKeys";
import {
  BUYER_COTS_READONLY_KEYS,
  mapOnboardingToAssessmentForm,
} from "../../../../constants/buyerCotsOnboardingMapping";
import { useState, useEffect, useRef, useMemo } from "react";
import { useNavigate, useParams, Navigate, useLocation } from "react-router-dom";
import { toast } from "react-toastify";
import Button from "../../../UI/Button";
import {
  ChevronLeftCircle,
  ChevronRightCircle,
  Send,
  Save,
  Loader2,
  FileCheck,
} from "lucide-react";
import CardConfirmation from "../../../UI/CardConfirmation";
import UseCase from "./UseCase";
import VendorEvaluation from "./VendorEvaluation";
import Readiness from "./Readiness";
import RiskProfile from "./RiskProfile";
import VendoeRisk from "./VendorRisk";
import Implementation from "./Implementation";
import Evidence from "./Evidence";
// import AutoGenerated from "./AutoGenerated";
import StepBuyerCotsPreview from "./StepBuyerCotsPreview";
import { BUYER_COTS_ASSESSMENT } from "../../../../constants/buyerCOTSData 1";
import { BUYER_COTS_TAB_STEPS } from "./buyerCotsTabs";

const BASE_URL =
  import.meta.env.VITE_BASE_URL ?? "http://localhost:5003/api/v1";
// After Evidence go to Review; Auto-Generated step commented out
const TOTAL_STEPS = 9;

const BUYER_COTS_SECTION_KEYS = [
  "organizationProfile",
  "useCase",
  "vendorEvaluation",
  "readiness",
  "riskProfile",
  "vendorRisk",
  "implementation",
  "evidence",
] as const;

type BuyerAssessmentPrefillState = {
  prefillVendorName?: unknown;
  prefillProductName?: unknown;
  vendorName?: unknown;
  productName?: unknown;
};

function hasValue(
  formData: Record<string, string>,
  key: string,
  isMultiselect: boolean,
): boolean {
  const v = formData[key];
  if (v == null || v === "") return false;
  if (isMultiselect) {
    try {
      const parsed = JSON.parse(v);
      return Array.isArray(parsed) && parsed.length > 0;
    } catch {
      return false;
    }
  }
  return String(v).trim().length > 0;
}

function isBuyerCotsStepValid(
  stepIndex: number,
  formData: Record<string, string>,
): boolean {
  if (stepIndex < 0 || stepIndex >= BUYER_COTS_SECTION_KEYS.length)
    return true;
  const sectionKey = BUYER_COTS_SECTION_KEYS[stepIndex];
  const keys = BUYER_COTS_FIELD_KEYS[sectionKey];
  const data = BUYER_COTS_ASSESSMENT[sectionKey];
  if (!keys || !data) return true;
  for (let i = 0; i < keys.length; i++) {
    const key = keys[i];
    const config = data[i as keyof typeof data];
    if (!config || config.required !== "true") continue;
    const isMultiselect = !!(config as { multiselect?: boolean }).multiselect;
    if (!hasValue(formData, key, isMultiselect)) return false;
  }
  return true;
}

function getBuyerCotsStepFieldErrors(
  stepIndex: number,
  formData: Record<string, string>,
): Record<string, string> {
  const errors: Record<string, string> = {};
  if (stepIndex < 0 || stepIndex >= BUYER_COTS_SECTION_KEYS.length)
    return errors;
  const sectionKey = BUYER_COTS_SECTION_KEYS[stepIndex];
  const keys = BUYER_COTS_FIELD_KEYS[sectionKey];
  const data = BUYER_COTS_ASSESSMENT[sectionKey];
  if (!keys || !data) return errors;
  for (let i = 0; i < keys.length; i++) {
    const key = keys[i];
    const config = data[i as keyof typeof data];
    if (!config || config.required !== "true") continue;
    const isMultiselect = !!(config as { multiselect?: boolean }).multiselect;
    if (!hasValue(formData, key, isMultiselect))
      errors[key] = "This field is required";
  }
  return errors;
}

const AUTO_GENERATED_KEYS = [
  "identifiedRisks",
  "riskDomainScores",
  "contextualMultipliers",
  "riskMitigation",
];

/** Form keys that store multiselect as JSON strings; send as parsed arrays for jsonb columns */
const MULTISELECT_JSON_KEYS = [
  "integrationSystems",
  "techStack",
  "implementationTeamComposition",
  "regulatoryRequirements",
  "impactedStakeholders",
  "vendorCertifications",
] as const;

function prepareSubmitPayload(
  data: Record<string, string>,
  riskMitigationMappingIds: number[],
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...data };
  for (const key of MULTISELECT_JSON_KEYS) {
    const v = out[key];
    if (typeof v === "string" && v.trim().length > 0) {
      try {
        const parsed = JSON.parse(v);
        if (Array.isArray(parsed)) out[key] = parsed;
      } catch {
        // leave as string if not valid JSON
      }
    }
  }
  if (riskMitigationMappingIds.length > 0) {
    out.riskMitigationMappingIds = riskMitigationMappingIds;
  }
  return out;
}

const BuyerAssessment = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { id: assessmentIdFromUrl } = useParams();
  const [assessmentId, setAssessmentId] = useState<string | null>(
    assessmentIdFromUrl ?? null,
  );
  const [currentStep, setCurrentStep] = useState(0);
  const [allStepsFilled, setAllStepsFilled] = useState(false);
  const [formData, setFormData] = useState({
    ...BUYER_COTS_INITIAL_STATE,
    integrationSystemsOther: "",
  });
  const [submitError, setSubmitError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [savingDraft, setSavingDraft] = useState(false);
  const [autoGeneratedLoading, setAutoGeneratedLoading] = useState(false);
  const [onboardingFetched, setOnboardingFetched] = useState(false);
  const [draftLoaded, setDraftLoaded] = useState(false);
  const [accessDenied, setAccessDenied] = useState(false);
  const [riskMitigationMappingIds, setRiskMitigationMappingIds] = useState<
    number[]
  >([]);
  const [validationAttemptedSteps, setValidationAttemptedSteps] = useState<
    Set<number>
  >(new Set());
  const autoGeneratedFetchedRef = useRef(false);

  const handleContinue = async () => {
    if (
      currentStep < BUYER_COTS_SECTION_KEYS.length &&
      !isBuyerCotsStepValid(currentStep, formData)
    ) {
      setValidationAttemptedSteps((prev) => new Set(prev).add(currentStep));
      return;
    }
    const saved = await handleSaveDraft({ silent: true });
    if (saved) setCurrentStep((prev) => Math.min(prev + 1, TOTAL_STEPS - 1));
  };
  const handleBack = () => setCurrentStep((prev) => Math.max(0, prev - 1));
  const handleBackToAssessments = () => navigate("/assessments");

  // Sync assessmentId from URL (e.g. when navigating to /buyerAssessment/:id)
  useEffect(() => {
    if (assessmentIdFromUrl) setAssessmentId(assessmentIdFromUrl);
  }, [assessmentIdFromUrl]);

  // Prefill vendor/product when user starts from AI Vendor Directory create-assessment action.
  useEffect(() => {
    if (assessmentIdFromUrl) return;
    const params = new URLSearchParams(location.search);
    const state = (location.state ?? {}) as BuyerAssessmentPrefillState;
    const pickText = (value: unknown): string =>
      typeof value === "string" ? value.trim() : "";

    const vendorName =
      pickText(state.prefillVendorName) ||
      pickText(state.vendorName) ||
      pickText(params.get("vendorName"));
    const productName =
      pickText(state.prefillProductName) ||
      pickText(state.productName) ||
      pickText(params.get("productName"));

    if (!vendorName && !productName) return;
    setFormData((prev) => {
      const next = { ...prev };
      if (vendorName) next.vendorName = vendorName;
      if (productName) next.productName = productName;
      if (
        next.vendorName === prev.vendorName &&
        next.productName === prev.productName
      ) {
        return prev;
      }
      return next;
    });
  }, [assessmentIdFromUrl, location.search, location.state]);

  // Load draft by id when URL has /buyerAssessment/:id
  useEffect(() => {
    if (!assessmentIdFromUrl || draftLoaded) return;
    const token = sessionStorage.getItem("bearerToken");
    if (!token) return;
    setDraftLoaded(true); // prevent re-run
    fetch(`${BASE_URL}/buyerCotsAssessment/${assessmentIdFromUrl}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    })
      .then(async (res) => {
        const result = await res.json().catch(() => ({}));
        if (res.status === 403 || (!res.ok && !result?.success)) {
          setAccessDenied(true);
          return;
        }
        if (result?.success && result?.data) {
          const d = result.data;
          const status = String(d.status ?? "").toLowerCase();
          if (status === "completed" || status === "submitted") {
            toast.info("This assessment is completed and cannot be edited.");
            navigate("/assessments", { replace: true });
            return;
          }
          setAssessmentId(d.assessmentId);
          const patch: Record<string, string> = {};
          const draftKeys = [
            "organizationName",
            "industrySector",
            "employeeCount",
            "operatingRegions",
            "businessPainPoint",
            "expectedOutcomes",
            "owningDepartment",
            "budgetRange",
            "targetTimeline",
            "criticality",
            "vendorName",
            "productName",
            "requirementGaps",
            "digitalMaturityLevel",
            "dataGovernanceMaturity",
            "aiGovernanceBoard",
            "aiEthicsPolicy",
            "dataSensitivity",
            "riskAppetite",
            "decisionStakes",
            "vendorValidationApproach",
            "vendorSecurityPosture",
            "pilotRolloutPlan",
            "rollbackCapability",
            "changeManagementPlan",
            "monitoringDataAvailable",
            "auditLogsAvailable",
            "testingResultsAvailable",
            "identifiedRisks",
            "riskDomainScores",
            "contextualMultipliers",
            "riskMitigation",
          ];
          draftKeys.forEach((key) => {
            const v = d[key];
            if (v != null)
              patch[key] = Array.isArray(v) ? JSON.stringify(v) : String(v);
          });
          if (typeof d.integrationSystems === "string")
            patch.integrationSystems = d.integrationSystems;
          else if (Array.isArray(d.integrationSystems))
            patch.integrationSystems = JSON.stringify(d.integrationSystems);
          if (typeof d.techStack === "string") patch.techStack = d.techStack;
          else if (Array.isArray(d.techStack))
            patch.techStack = JSON.stringify(d.techStack);
          if (typeof d.implementationTeamComposition === "string")
            patch.implementationTeamComposition =
              d.implementationTeamComposition;
          else if (Array.isArray(d.implementationTeamComposition))
            patch.implementationTeamComposition = JSON.stringify(
              d.implementationTeamComposition,
            );
          if (typeof d.regulatoryRequirements === "string")
            patch.regulatoryRequirements = d.regulatoryRequirements;
          else if (Array.isArray(d.regulatoryRequirements))
            patch.regulatoryRequirements = JSON.stringify(
              d.regulatoryRequirements,
            );
          if (typeof d.impactedStakeholders === "string")
            patch.impactedStakeholders = d.impactedStakeholders;
          else if (Array.isArray(d.impactedStakeholders))
            patch.impactedStakeholders = JSON.stringify(d.impactedStakeholders);
          if (typeof d.vendorCertifications === "string")
            patch.vendorCertifications = d.vendorCertifications;
          else if (Array.isArray(d.vendorCertifications))
            patch.vendorCertifications = JSON.stringify(d.vendorCertifications);
          if (d.integrationSystemsOther != null)
            patch.integrationSystemsOther = String(d.integrationSystemsOther);
          if (Array.isArray(d.riskMitigationMappingIds))
            setRiskMitigationMappingIds(
              d.riskMitigationMappingIds
                .map((n: number) => Number(n))
                .filter((n: number) => !Number.isNaN(n)),
            );
          setFormData((prev) => ({ ...prev, ...patch }));
          const orgId = d.organizationId;
          if (orgId) sessionStorage.setItem("organizationId", orgId);
        }
      })
      .catch(() => {
        /* keep draftLoaded true so we don't retry in a loop */
      });
  }, [assessmentIdFromUrl, draftLoaded, navigate]);

  // Fetch buyer onboarding for the current user's org and pre-fill auto-populated fields (read-only in UI)
  useEffect(() => {
    if (onboardingFetched) return;
    const token = sessionStorage.getItem("bearerToken");
    if (!token) return;

    setOnboardingFetched(true);

    const headers = {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    };

    const applyBuyerData = (result, isEditDraft: boolean) => {
      const buyer = result?.data?.buyer ?? null;
      if (buyer && result?.data?.organizationId) {
        sessionStorage.setItem("organizationId", result.data.organizationId);
      }
      // When editing a draft, do not overwrite form with onboarding — use draft data only.
      if (isEditDraft) return;
      const patch = mapOnboardingToAssessmentForm(buyer);
      if (Object.keys(patch).length) {
        setFormData((prev) => ({ ...prev, ...patch }));
      }
    };

    const isEditDraft = Boolean(assessmentIdFromUrl);
    // 1) GET /buyerOnboarding/me – uses JWT to get user's org and return buyer onboarding
    fetch(`${BASE_URL}/buyerOnboarding/me`, { method: "GET", headers })
      .then((res) => res.json())
      .then((result) => {
        if (result?.data != null) {
          applyBuyerData(result, isEditDraft);
          return;
        }
        throw new Error("No data");
      })
      .catch(() => {
        const organizationId = sessionStorage.getItem("organizationId");
        if (!organizationId) return;
        return fetch(
          `${BASE_URL}/orgOnboarding/${encodeURIComponent(organizationId)}`,
          {
            method: "GET",
            headers,
          },
        )
          .then((res) => res.json())
          .then((r) => applyBuyerData(r, isEditDraft));
      })
      .catch(() => setOnboardingFetched(false));
  }, [onboardingFetched, assessmentIdFromUrl]);

  // Auto Generated step commented out: after Evidence go to Review
  // useEffect(() => {
  //   if (currentStep !== 8 || autoGeneratedFetchedRef.current) return;
  //   const token = sessionStorage.getItem("bearerToken");
  //   const organizationId = sessionStorage.getItem("organizationId");
  //   if (!token || !organizationId) return;
  //   autoGeneratedFetchedRef.current = true;
  //   setAutoGeneratedLoading(true);
  //   fetch(`${BASE_URL}/buyerCotsAssessment/autoGenerated`, {
  //     method: "POST",
  //     headers: {
  //       "Content-Type": "application/json",
  //       Authorization: `Bearer ${token}`,
  //     },
  //     body: JSON.stringify({ organizationId, ...formData }),
  //   })
  //     .then((res) => res.json())
  //     .then((result) => {
  //       if (result.data) {
  //         setFormData((prev) => {
  //           const next = { ...prev };
  //           AUTO_GENERATED_KEYS.forEach((key) => {
  //             if (result.data[key] != null)
  //               next[key] = String(result.data[key]);
  //           });
  //           return next;
  //         });
  //         const ids = result.data.riskMitigationMappingIds;
  //         if (Array.isArray(ids)) {
  //           setRiskMitigationMappingIds(
  //             ids.map((id) => Number(id)).filter((n) => !Number.isNaN(n)),
  //           );
  //         }
  //       }
  //     })
  //     .catch(() => {
  //       autoGeneratedFetchedRef.current = false;
  //     })
  //     .finally(() => setAutoGeneratedLoading(false));
  // }, [currentStep]);

  const handleSaveDraft = async (options?: { silent?: boolean }): Promise<boolean> => {
    const silent = options?.silent === true;
    setSubmitError("");
    const token = sessionStorage.getItem("bearerToken");
    const organizationId = sessionStorage.getItem("organizationId");
    if (!token) {
      setSubmitError("Please log in again.");
      return false;
    }
    if (!organizationId) {
      setSubmitError(
        "Organization context missing. Please complete onboarding or log in again.",
      );
      return false;
    }
    if (!silent) setSavingDraft(true);
    try {
      const payload = {
        organizationId,
        ...prepareSubmitPayload(formData, riskMitigationMappingIds),
      };
      if (assessmentId) payload.assessmentId = assessmentId;
      const response = await fetch(
        `${BASE_URL}/buyerCotsAssessment/save-draft`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify(payload),
        },
      );
      let result: { message?: string; assessmentId?: string } = {};
      try {
        const text = await response.text();
        if (text) result = JSON.parse(text);
      } catch {
        result = {
          message: response.ok ? "Draft saved" : "Failed to save draft",
        };
      }
      if (!response.ok)
        throw new Error(result.message || "Failed to save draft");
      const savedId =
        result.assessmentId != null ? String(result.assessmentId) : null;
      if (savedId) {
        setAssessmentId(savedId);
        if (!assessmentIdFromUrl) {
          window.history.replaceState(null, "", `/buyerAssessment/${savedId}`);
        }
      }
      if (!silent) toast.success("Draft saved.");
      return true;
    } catch (err) {
      setSubmitError(
        err instanceof Error ? err.message : "Failed to save draft",
      );
      return false;
    } finally {
      if (!silent) setSavingDraft(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitError("");
    setSubmitting(true);
    const token = sessionStorage.getItem("bearerToken");
    const organizationId = sessionStorage.getItem("organizationId");
    if (!organizationId) {
      setSubmitError(
        "Organization context missing. Please complete onboarding or log in again.",
      );
      setSubmitting(false);
      return;
    }
    try {
      const payload = {
        organizationId,
        ...prepareSubmitPayload(formData, riskMitigationMappingIds),
      };
      if (assessmentId) payload.assessmentId = assessmentId;
      const response = await fetch(`${BASE_URL}/buyerCotsAssessment`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });
      const result = await response.json();
      if (!response.ok) {
        throw new Error(result.message || "Failed to submit assessment");
      }
      const submittedId =
        result.assessmentId != null
          ? String(result.assessmentId)
          : assessmentId != null
            ? String(assessmentId)
            : "";
      if (submittedId) {
        navigate(
          `/buyer-vendor-risk-report/${encodeURIComponent(submittedId)}`,
          { replace: true },
        );
      } else {
        navigate("/reports", { replace: true });
      }
    } catch (err) {
      setSubmitError(err.message || "Failed to submit assessment");
    } finally {
      setSubmitting(false);
    }
  };

  const stepFieldErrors = useMemo(
    () => getBuyerCotsStepFieldErrors(currentStep, formData),
    [currentStep, formData],
  );
  const effectiveFieldErrors = useMemo(
    () =>
      validationAttemptedSteps.has(currentStep) ? stepFieldErrors : {},
    [validationAttemptedSteps, currentStep, stepFieldErrors],
  );
  const disabledSteps = useMemo(() => {
    const disabled: number[] = [];
    for (let i = 0; i < TOTAL_STEPS; i++) {
      if (
        i < BUYER_COTS_SECTION_KEYS.length &&
        !isBuyerCotsStepValid(i, formData)
      ) {
        for (let j = i + 1; j < TOTAL_STEPS; j++) disabled.push(j);
        break;
      }
    }
    return disabled;
  }, [formData]);

  const stepIconNodes = useMemo(
    () =>
      BUYER_COTS_TAB_STEPS.map((s) =>
        s.icon ? <s.icon key={s.id} size={18} /> : null
      ),
    [],
  );

  const tabStepsWithContent = useMemo(
    () =>
      BUYER_COTS_TAB_STEPS.map((step, index) => {
        const iconNode = stepIconNodes[index];
        const commonHeader = {
          title: step.label,
          subTitle: step.subTitle,
          icon: iconNode,
        };
        const fieldErrors =
          index === currentStep && index < BUYER_COTS_SECTION_KEYS.length
            ? effectiveFieldErrors
            : undefined;
        let content: React.ReactNode;
        if (index === 0) {
          content = (
            <OrganizationProfile
              data={BUYER_COTS_ASSESSMENT.organizationProfile}
              formData={formData}
              setFormData={setFormData}
              readOnlyKeys={BUYER_COTS_READONLY_KEYS}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 1) {
          content = (
            <UseCase
              data={BUYER_COTS_ASSESSMENT.useCase}
              formData={formData}
              setFormData={setFormData}
              readOnlyKeys={BUYER_COTS_READONLY_KEYS}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 2) {
          content = (
            <VendorEvaluation
              data={BUYER_COTS_ASSESSMENT.vendorEvaluation}
              formData={formData}
              setFormData={setFormData}
              readOnlyKeys={BUYER_COTS_READONLY_KEYS}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 3) {
          content = (
            <Readiness
              data={BUYER_COTS_ASSESSMENT.readiness}
              formData={formData}
              setFormData={setFormData}
              readOnlyKeys={BUYER_COTS_READONLY_KEYS}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 4) {
          content = (
            <RiskProfile
              data={BUYER_COTS_ASSESSMENT.riskProfile}
              formData={formData}
              setFormData={setFormData}
              readOnlyKeys={BUYER_COTS_READONLY_KEYS}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 5) {
          content = (
            <VendoeRisk
              data={BUYER_COTS_ASSESSMENT.vendorRisk}
              formData={formData}
              setFormData={setFormData}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 6) {
          content = (
            <Implementation
              data={BUYER_COTS_ASSESSMENT.implementation}
              formData={formData}
              setFormData={setFormData}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        } else if (index === 7) {
          content = (
            <Evidence
              data={BUYER_COTS_ASSESSMENT.evidence}
              formData={formData}
              setFormData={setFormData}
              fieldErrors={fieldErrors}
              {...commonHeader}
            />
          );
        // Auto-Generated step commented out: after Evidence (index 7) go to Review (index 8)
        } else if (index === 8) {
          content = (
            <StepBuyerCotsPreview formData={formData} {...commonHeader} />
          );
        }
        return {
          id: step.id,
          label: step.label,
          icon: step.icon,
          content,
        };
      }),
    [
      formData,
      stepIconNodes,
      currentStep,
      effectiveFieldErrors,
    ],
  );

  const completedStepsForProgress = Array.from(
    { length: currentStep },
    (_, i) => i,
  );

  if (assessmentIdFromUrl && accessDenied) {
    return <Navigate to="/accessDenied" replace />;
  }

  return (
    <div className="sec_user_page org_settings_page">
      <div className="org_settings_header page_header_align">
        <div className="org_settings_headers page_header_row">
          <span className="icon_size_header" aria-hidden>
            <FileCheck size={24} className="header_icon_svg" />
          </span>
          <div className="page_header_title_block">
            <h1 className="org_settings_title page_header_title">Buyer COTS Assessment</h1>
            <p className="org_settings_subtitle page_header_subtitle">
              Complete and submit your buyer assessment.
            </p>
          </div>
        </div>
      </div>
      {submitting && (
        <div
          className="vendor_attestation_submit_overlay"
          role="status"
          aria-live="polite"
          aria-label="Submitting assessment"
        >
          <div className="vendor_attestation_submit_overlay_content">
            <Loader2 size={32} className="vendor_attestation_submit_overlay_loader" aria-hidden />
            <p>Submitting assessment…</p>
            <p className="vendor_attestation_submit_overlay_hint">Please wait. Do not close or refresh.</p>
          </div>
        </div>
      )}
      <div className="form_card_centered">
      <CardContainerOnBoarding>
        <button
          type="button"
          className="form_back_to_assessments"
          onClick={() => navigate("/assessments")}
          aria-label="Back to Assessments"
          disabled={submitting}
        >
          <ChevronLeftCircle size={18} />
          <span>Back to Assessments</span>
        </button>
        <form onSubmit={handleSubmit}>
          {allStepsFilled ? (
            <CardOnBoarding className="card_vendor">
              <CardConfirmation />
            </CardOnBoarding>
          ) : (
            <>
              <MultiStepTabs
                steps={tabStepsWithContent}
                currentStep={currentStep}
                onStepChange={(step) => {
                  if (submitting) return;
                  setCurrentStep(step);
                }}
                completedSteps={completedStepsForProgress}
                disabledSteps={disabledSteps}
                canGoNext={
                  currentStep >= TOTAL_STEPS - 1 ||
                  isBuyerCotsStepValid(currentStep, formData)
                }
                className="vendor_onboarding_tabs"
              />
              <CardOnBoarding className="card_vendor">
                {submitError && (
                  <p
                    className="vendor_form_block_error"
                    role="alert"
                    style={{ marginBottom: 8 }}
                  >
                    {submitError}
                  </p>
                )}
                <div className="vendor_action_btns">
                  {!allStepsFilled && (
                    <div className="action_back">
                      <Button
                        type="button"
                        onClick={
                          currentStep === 0
                            ? handleBackToAssessments
                            : handleBack
                        }
                        disabled={submitting}
                        className="back_btn"
                      >
                        <span>
                          <ChevronLeftCircle size={16} />
                          Back
                        </span>
                      </Button>
                    </div>
                  )}
                  <div className="last_two_btns">
                    {!allStepsFilled && (
                      <div className="vendor_attestation_save_draft_wrapper">
                        <Button
                          type="button"
                          onClick={handleSaveDraft}
                          disabled={savingDraft || submitting}
                          className="vendor_attestation_save_draft_btn_form"
                        >
                          <span>
                            <Save size={16} />
                            {savingDraft ? " Saving…" : " Save draft"}
                          </span>
                        </Button>
                      </div>
                    )}

                    {currentStep < TOTAL_STEPS - 1 && !allStepsFilled && (
                      <div className="action_continue_btn">
                        <Button
                          type="button"
                          onClick={handleContinue}
                          disabled={submitting}
                          className="continue_btn"
                        >
                          <span>
                            Continue <ChevronRightCircle size={16} />
                          </span>
                        </Button>
                      </div>
                    )}

                    {currentStep === TOTAL_STEPS - 1 && !allStepsFilled && (
                      <div className="action_submit_btn">
                        <Button type="submit" className="submit_btn_vendor" disabled={submitting}>
                          <span>
                            Submit <Send size={16} />
                          </span>
                        </Button>
                      </div>
                    )}
                  </div>
                </div>
              </CardOnBoarding>
            </>
          )}
        </form>
      </CardContainerOnBoarding>
      </div>
    </div>
  );
};

export default BuyerAssessment;
