import type { ReactNode } from "react";
import HeaderForVendor from "../../VendorOnboarding/HeaderForVendor";
import FormField from "../../../UI/FormField";
import { VENDOR_COTS_FIELD_KEYS } from "../../../../constants/vendorCotsAssessmentKeys";

const AUTO_KEYS = VENDOR_COTS_FIELD_KEYS.autoGenerated;

interface StepAutoGeneratedProps {
  data: Record<string, { label: string; placeholder: string; required: string | boolean }>;
  formData?: Record<string, string>;
  setFormData?: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  /** Tab icon to show in header (same as in tabs) */
  icon?: ReactNode;
}

function StepAutoGenerated({ data, formData = {}, icon }: StepAutoGeneratedProps) {
  return (
    <>
      <div className="step_form_body">
        <HeaderForVendor
          title_vendor="Auto-Generated"
          className="header_for_vendor"
          icon={icon}
        />
        <p className="vendor_preview_intro" style={{ marginBottom: "1rem" }}>
          The following are generated from your responses.
        </p>
        <div className="step_form_right">
          <div>
            {AUTO_KEYS.map((key, i) => {
              const field = data[i];
              if (!field) return null;
              return (
                <div key={key} className="form_fields_vendor">
                  <FormField
                    label={field.label}
                    mandatory={false}
                    tooltipText={field.placeholder}
                  >
                    <div className="vendor_preview_value" style={{ padding: "0.5rem 0", color: "#64748b" }}>
                      {formData[key] ?? field.placeholder}
                    </div>
                  </FormField>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </>
  );
}

export default StepAutoGenerated;
