import { useEffect, useState, useMemo } from "react";
import { useNavigate, useParams, Navigate } from "react-router-dom";
import CardContainerOnBoarding from "../../../UI/CardContainerOnBoarding";
import CardOnBoarding from "../../../UI/CardOnBoarding";
import MultiStepTabs from "../../../UI/MultiStepTabs";
import VendorCotsDynamicStep from "./VendorCotsDynamicStep";
// import StepAutoGenerated from "./StepAutoGenerated";
import StepVendorCotsPreview from "./StepVendorCotsPreview";
import Button from "../../../UI/Button";
import {
  ChevronLeftCircle,
  ChevronRightCircle,
  Send,
  Save,
  Search,
  Puzzle,
  AlertTriangle,
  BarChart2,
  Shield,
  Sparkles,
  FileCheck,
  Loader2,
} from "lucide-react";
import { toast } from "react-toastify";
import { VENDOR_COTS_DATA } from "../../../../constants/vendorCotsData";
import {
  VENDOR_COTS_INITIAL_STATE,
  VENDOR_COTS_FIELD_KEYS,
} from "../../../../constants/vendorCotsAssessmentKeys";
import { VENDOR_COTS_FORM_SECTIONS } from "../../../../constants/vendorCotsFormSchema";
import { VENDOR_COTS_TAB_STEPS } from "./vendorCotsTabs";
import "../../../../styles/card.css";
import "../../VendorOnboarding/vendor_onboarding.css";
import "../../UserManagement/user_management.css";
import "../../VendorAttestations/vendor_attestation_preview.css";

const BASE_URL =
  import.meta.env.VITE_BASE_URL ?? "http://localhost:5003/api/v1";
// After step 5 (Customer Risk Mitigation) go to preview; Auto-Generated step commented out
const TOTAL_STEPS = 6;

/** Explicit icon elements for each step so icons always render in header_title_vendor */
const VENDOR_COTS_STEP_ICONS: React.ReactNode[] = [
  <Search key="customer-discovery" size={18} />,
  <Puzzle key="solution-fit" size={18} />,
  <AlertTriangle key="customer-risk-context" size={18} />,
  <BarChart2 key="competitive-analysis" size={18} />,
  <Shield key="customer-risk-mitigation" size={18} />,
  // <Sparkles key="auto-generated" size={18} />,
  <FileCheck key="review" size={18} />,
];

function hasValue(
  formData: Record<string, string>,
  key: string,
  isMultiselect: boolean,
): boolean {
  const v = formData[key];
  if (v == null || v === "") return false;
  if (isMultiselect) {
    try {
      const parsed = JSON.parse(v);
      return Array.isArray(parsed) && parsed.length > 0;
    } catch {
      return false;
    }
  }
  return String(v).trim().length > 0;
}

function isVendorCotsStepValid(
  stepIndex: number,
  formData: Record<string, string>,
): boolean {
  if (stepIndex >= VENDOR_COTS_FORM_SECTIONS.length) return true;
  const section = VENDOR_COTS_FORM_SECTIONS[stepIndex];
  for (const field of section.fields) {
    if (!field.required) continue;
    const isMultiselect = field.inputType === "multiselect";
    if (!hasValue(formData, field.key, isMultiselect)) return false;
  }
  return true;
}

function getVendorCotsStepFieldErrors(
  stepIndex: number,
  formData: Record<string, string>,
): Record<string, string> {
  const errors: Record<string, string> = {};
  if (stepIndex >= VENDOR_COTS_FORM_SECTIONS.length) return errors;
  const section = VENDOR_COTS_FORM_SECTIONS[stepIndex];
  for (const field of section.fields) {
    if (!field.required) continue;
    const isMultiselect = field.inputType === "multiselect";
    if (!hasValue(formData, field.key, isMultiselect))
      errors[field.key] = "This field is required";
  }
  return errors;
}

const VendorCOTSMain = () => {
  const navigate = useNavigate();
  const { assessmentId: assessmentIdFromUrl } = useParams<{
    assessmentId?: string;
  }>();

  useEffect(() => {
    document.title = "AI-Q | Vendor COTS";
  }, []);

  const [currentStep, setCurrentStep] = useState(0);
  const [formData, setFormData] = useState<Record<string, string>>({
    ...VENDOR_COTS_INITIAL_STATE,
  });
  const [submitError, setSubmitError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [draftAssessmentId, setDraftAssessmentId] = useState<string | null>(
    assessmentIdFromUrl ?? null,
  );
  const [savingDraft, setSavingDraft] = useState(false);
  const [draftLoaded, setDraftLoaded] = useState(false);
  const [accessDenied, setAccessDenied] = useState(false);
  const [validationAttemptedSteps, setValidationAttemptedSteps] = useState<
    Set<number>
  >(() => new Set());
  const [completedProductOptions, setCompletedProductOptions] = useState<
    { value: string; label: string }[]
  >([]);

  // Fetch vendor's completed products (for Solution Fit Product dropdown)
  useEffect(() => {
    const token = sessionStorage.getItem("bearerToken");
    if (!token) return;
    fetch(`${BASE_URL}/vendorSelfAttestation`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    })
      .then((res) => res.json())
      .then((result: { success?: boolean; attestations?: Array<{ id?: string; status?: string; product_name?: string | null }> }) => {
        if (!result?.success || !Array.isArray(result.attestations)) return;
        const completed = result.attestations.filter(
          (a) => String(a.status ?? "").toUpperCase() === "COMPLETED" && a.id
        );
        const opts = completed.map((a) => ({
          value: String(a.id),
          label: (a.product_name ?? "").trim() || `Product ${a.id}`,
        }));
        setCompletedProductOptions(opts);
      })
      .catch(() => {});
  }, []);

  // When starting a new assessment (no id), ensure org context from onboarding so form can be saved
  useEffect(() => {
    if (assessmentIdFromUrl) return;
    const token = sessionStorage.getItem("bearerToken");
    if (!token || sessionStorage.getItem("organizationId")) return;
    fetch(`${BASE_URL}/vendorOnboarding`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    })
      .then((res) => res.json())
      .then((result) => {
        const orgId = result?.data?.organizationId ?? result?.organizationId;
        if (orgId) sessionStorage.setItem("organizationId", String(orgId));
      })
      .catch(() => {});
  }, [assessmentIdFromUrl]);

  // Load draft when opening Edit from assessments list (URL has :assessmentId)
  useEffect(() => {
    const id = assessmentIdFromUrl ?? null;
    if (!id) {
      setDraftLoaded(true);
      return;
    }
    setDraftAssessmentId(id);
    const token = sessionStorage.getItem("bearerToken");
    if (!token) {
      setDraftLoaded(true);
      return;
    }
    let cancelled = false;
    const organizationId = sessionStorage.getItem("organizationId");
    const query = organizationId
      ? `?organizationId=${encodeURIComponent(organizationId)}`
      : "";
    fetch(`${BASE_URL}/vendorCotsAssessment/${id}${query}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    })
      .then(async (res) => {
        const result = await res.json().catch(() => ({}));
        if (cancelled) return;
        if (res.status === 403 || (!res.ok && !result?.success)) {
          setAccessDenied(true);
          setDraftLoaded(true);
          return;
        }
        if (!result?.success || !result?.data) {
          setDraftLoaded(true);
          return;
        }
        const d = result.data as Record<string, unknown>;
        const status = String(d.status ?? "").toLowerCase();
        if (status === "completed" || status === "submitted") {
          toast.info("This assessment is completed and cannot be edited.");
          navigate("/assessments", { replace: true });
          return;
        }
        const draftKeys = [
          ...VENDOR_COTS_FIELD_KEYS.customerDiscovery,
          ...VENDOR_COTS_FIELD_KEYS.solutionFit,
          ...VENDOR_COTS_FIELD_KEYS.customerRiskContext,
          ...VENDOR_COTS_FIELD_KEYS.competitiveAnalysis,
          ...VENDOR_COTS_FIELD_KEYS.customerRiskMitigation,
          ...VENDOR_COTS_FIELD_KEYS.autoGenerated,
        ];
        const patch: Record<string, string> = { ...VENDOR_COTS_INITIAL_STATE };
        draftKeys.forEach((key) => {
          const v = d[key];
          if (v !== undefined && v !== null) {
            patch[key] = Array.isArray(v)
              ? JSON.stringify(v)
              : typeof v === "object"
                ? JSON.stringify(v)
                : String(v);
          }
        });
        setFormData(patch);
      })
      .catch(() => {
        if (!cancelled)
          toast.error("Failed to load draft. It may have been deleted.");
      })
      .finally(() => {
        if (!cancelled) setDraftLoaded(true);
      });
    return () => {
      cancelled = true;
    };
  }, [assessmentIdFromUrl, navigate]);

  const handleContinue = async () => {
    if (
      currentStep < VENDOR_COTS_FORM_SECTIONS.length &&
      !isVendorCotsStepValid(currentStep, formData)
    ) {
      setValidationAttemptedSteps((prev) => new Set(prev).add(currentStep));
      return;
    }
    const saved = await handleSaveDraft({ silent: true });
    if (saved) setCurrentStep((prev) => Math.min(prev + 1, TOTAL_STEPS - 1));
  };

  const handleBack = () => setCurrentStep((prev) => Math.max(0, prev - 1));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError("");
    setSubmitting(true);
    const token = sessionStorage.getItem("bearerToken");
    const organizationId = sessionStorage.getItem("organizationId");
    if (!token) {
      setSubmitError("Please log in to submit.");
      setSubmitting(false);
      return;
    }
    if (!organizationId) {
      setSubmitError(
        "Organization context missing. Please complete onboarding or log in again.",
      );
      setSubmitting(false);
      return;
    }
    try {
      const payload: Record<string, unknown> = { organizationId, ...formData };
      if (draftAssessmentId) payload.assessmentId = draftAssessmentId;
      const multiselectKeys = [
        "productFeatures",
        "regulatoryRequirements",
        "customerSpecificRisks",
      ];
      multiselectKeys.forEach((k) => {
        if (payload[k] === "" || payload[k] == null) payload[k] = "[]";
      });
      const response = await fetch(`${BASE_URL}/vendorCotsAssessment`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });
      const result = await response.json();
      if (!response.ok) {
        if (response.status === 403) {
          toast.info("This assessment is completed and cannot be modified.");
          navigate("/assessments", { replace: true });
          return;
        }
        throw new Error(result.message || "Failed to submit assessment");
      }
      navigate("/reports", { replace: true });
    } catch (err) {
      setSubmitError(
        err instanceof Error ? err.message : "Failed to submit assessment",
      );
    } finally {
      setSubmitting(false);
    }
  };

  const handleSaveDraft = async (options?: { silent?: boolean }): Promise<boolean> => {
    const silent = options?.silent === true;
    const token = sessionStorage.getItem("bearerToken");
    const organizationId = sessionStorage.getItem("organizationId");
    if (!token) {
      setSubmitError("Please log in to save draft.");
      return false;
    }
    if (!organizationId) {
      setSubmitError(
        "Organization context missing. Please complete onboarding or log in again.",
      );
      return false;
    }
    if (!silent) setSavingDraft(true);
    setSubmitError("");
    try {
      const payload: Record<string, unknown> = { organizationId, ...formData };
      if (draftAssessmentId) payload.assessmentId = draftAssessmentId;
      const multiselectKeys = [
        "productFeatures",
        "regulatoryRequirements",
        "customerSpecificRisks",
      ];
      multiselectKeys.forEach((k) => {
        if (payload[k] === "" || payload[k] == null) payload[k] = "[]";
      });
      const response = await fetch(
        `${BASE_URL}/vendorCotsAssessment/save-draft`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify(payload),
        },
      );
      let result: { message?: string; assessmentId?: string | number } = {};
      try {
        result = await response.json();
      } catch {
        result = { message: "Invalid response from server" };
      }
      if (!response.ok) {
        if (response.status === 403) {
          toast.info(
            "This assessment is completed and cannot be changed back to draft.",
          );
          navigate("/assessments", { replace: true });
          return false;
        }
        const msg =
          result?.message || `Failed to save draft (${response.status})`;
        setSubmitError(msg);
        throw new Error(msg);
      }
      const savedId =
        result.assessmentId != null ? String(result.assessmentId) : null;
      if (savedId) {
        setDraftAssessmentId(savedId);
        if (!draftAssessmentId) {
          navigate(`/vendorcots/${savedId}`, { replace: true });
        }
      }
      if (!silent) toast.success("Draft saved.");
      return true;
    } catch (err) {
      setSubmitError(
        err instanceof Error ? err.message : "Failed to save draft",
      );
      return false;
    } finally {
      if (!silent) setSavingDraft(false);
    }
  };

  const stepFieldErrors = useMemo(
    () => getVendorCotsStepFieldErrors(currentStep, formData),
    [currentStep, formData],
  );
  const effectiveFieldErrors = useMemo(
    () => (validationAttemptedSteps.has(currentStep) ? stepFieldErrors : {}),
    [validationAttemptedSteps, currentStep, stepFieldErrors],
  );

  const disabledSteps = useMemo(() => {
    const disabled: number[] = [];
    for (let i = 0; i < TOTAL_STEPS; i++) {
      if (
        i < VENDOR_COTS_FORM_SECTIONS.length &&
        !isVendorCotsStepValid(i, formData)
      ) {
        for (let j = i + 1; j < TOTAL_STEPS; j++) disabled.push(j);
        break;
      }
    }
    return disabled;
  }, [formData]);

  const tabStepsWithContent = useMemo(
    () =>
      VENDOR_COTS_TAB_STEPS.map((step, index) => {
        const stepIconNode = VENDOR_COTS_STEP_ICONS[index];
        return {
          ...step,
          content:
            index < VENDOR_COTS_FORM_SECTIONS.length ? (
              <VendorCotsDynamicStep
                section={VENDOR_COTS_FORM_SECTIONS[index]}
                formData={formData}
                setFormData={setFormData}
                fieldErrors={effectiveFieldErrors}
                title={step.label}
                subTitle={undefined}
                icon={stepIconNode}
                completedProductOptions={completedProductOptions}
              />
            ) : (
              // After step 5 go to preview (Auto-Generated step commented out)
              <>
                <StepVendorCotsPreview formData={formData} completedProductOptions={completedProductOptions} />
              </>
            ),
        };
      }),
    [formData, effectiveFieldErrors, completedProductOptions],
  );

  const completedStepsForProgress = Array.from(
    { length: currentStep },
    (_, i) => i,
  );

  if (assessmentIdFromUrl && accessDenied) {
    return <Navigate to="/accessDenied" replace />;
  }

  return (
    <div className="sec_user_page org_settings_page">
      <div className="org_settings_header page_header_align">
        <div className="org_settings_headers page_header_row">
          <span className="icon_size_header" aria-hidden>
            <FileCheck size={24} className="header_icon_svg" />
          </span>
          <div className="page_header_title_block">
            <h1 className="org_settings_title page_header_title">Customer Assessment</h1>
            <p className="org_settings_subtitle page_header_subtitle">
              Complete and submit your customer assessment for sales opportunities.
            </p>
          </div>
        </div>
      </div>
      {submitting && (
        <div
          className="vendor_attestation_submit_overlay"
          role="status"
          aria-live="polite"
          aria-label="Submitting assessment"
        >
          <div className="vendor_attestation_submit_overlay_content">
            <Loader2 size={32} className="vendor_attestation_submit_overlay_loader" aria-hidden />
            <p>Submitting assessment…</p>
            <p className="vendor_attestation_submit_overlay_hint">Please wait. Do not close or refresh.</p>
          </div>
        </div>
      )}
      <div className="form_card_centered">
      <CardContainerOnBoarding>
        <button
          type="button"
          className="form_back_to_assessments"
          onClick={() => navigate("/assessments")}
          aria-label="Back to Assessments"
          disabled={submitting}
        >
          <ChevronLeftCircle size={18} />
          <span>Back to Assessments</span>
        </button>
        <form onSubmit={handleSubmit}>
          <MultiStepTabs
            steps={tabStepsWithContent}
            currentStep={currentStep}
            onStepChange={(step) => {
              if (submitting) return;
              setCurrentStep(step);
            }}
            completedSteps={completedStepsForProgress}
            disabledSteps={disabledSteps}
            canGoNext={
              currentStep >= TOTAL_STEPS - 1 ||
              isVendorCotsStepValid(currentStep, formData)
            }
            className="vendor_onboarding_tabs"
          />
          <CardOnBoarding className="card_vendor">
            <>
              {submitError && (
                  <p
                    className="vendor_form_block_error"
                    role="alert"
                    style={{ marginBottom: 8 }}
                  >
                    {submitError}
                  </p>
                )}
                <div className="vendor_action_btns">
                  <div className="action_back">
                    <Button
                      type="button"
                      onClick={currentStep > 0 ? handleBack : undefined}
                      disabled={currentStep === 0 || submitting}
                      className="back_btn"
                    >
                      <span>
                        <ChevronLeftCircle size={16} />
                        Back
                      </span>
                    </Button>
                  </div>
                  <div className="last_two_btns">
                    <div className="vendor_attestation_save_draft_wrapper">
                      <Button
                        type="button"
                        onClick={handleSaveDraft}
                        disabled={savingDraft || submitting}
                        className="vendor_attestation_save_draft_btn_form"
                      >
                        <span>
                          <Save size={16} />
                          {savingDraft ? " Saving…" : " Save Draft"}
                        </span>
                      </Button>
                    </div>

                    {currentStep < TOTAL_STEPS - 1 && (
                      <div className="action_continue_btn">
                        <Button
                          type="button"
                          onClick={handleContinue}
                          disabled={submitting}
                          className="continue_btn"
                        >
                          <span>
                            Continue <ChevronRightCircle size={16} />
                          </span>
                        </Button>
                      </div>
                    )}

                    {currentStep === TOTAL_STEPS - 1 && (
                      <div className="action_submit_btn">
                        <Button
                          type="submit"
                          className="submit_btn_vendor"
                          disabled={submitting}
                        >
                          <span>
                            Submit <Send size={16} />
                          </span>
                        </Button>
                      </div>
                    )}
                  </div>
                </div>
              </>
          </CardOnBoarding>
        </form>
      </CardContainerOnBoarding>
      </div>
    </div>
  );
};

export default VendorCOTSMain;
